### ISSUE TITLE
Misformatted IPv6 CIDR prevents security group rule from being found

### ISSUE THREAD

**Issue by sgrimm** [hashicorp/terraform-provider-aws#15982]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.13.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)
* `aws_security_group`
* `aws_security_group_rule`

### Terraform Configuration Files
```hcl
resource "aws_security_group" "example" {
  name   = "example"
  vpc_id = "your_vpc_id_here"
}

resource "aws_security_group_rule" "example" {
  security_group_id = aws_security_group.example.id

  type             = "ingress"
  protocol         = "tcp"
  from_port        = 80
  to_port          = 80
  cidr_blocks      = ["0.0.0.0/0"]
  # The next line is the malformed one: there is an extra "0" after the "::"
  ipv6_cidr_blocks = ["::0/0"]
}
```

### Debug Output
https://gist.github.com/sgrimm/a914a441fda5fd6cf92cb259d0edc9b6

### Expected Behavior
Security group rule is created successfully, or IPv6 CIDR is rejected as malformed.

### Actual Behavior
Security group rule is created on the AWS side (appears in AWS console) but Terraform thinks the creation failed:

```
Error: Error finding matching ingress Security Group Rule (sgrule-3448321076) for Group sg-066fb11ba0a148c78
```

Subsequent attempts to apply the plan fail because the rule already exists.

### Steps to Reproduce

1. Create a security group rule with an IPv6 CIDR block that has a `0` value adjacent to a `::`. The problem happens both with inline rules and `aws_security_group_rule` resources.
2. `terraform apply`

### Important Factoids
This is definitely user error; IPv6 formatting rules say it should be `::/0` rather than `::0/0`. Rejecting the CIDR as invalid would be totally reasonable.

**Comment by tylert** [comment]
With Terraform 0.14.2 and the 3.21.0 AWS provider (linux amd64 binaries), this bug would now appear the be present even if you use a properly-formatted `::/0`.

This error seems to occur only on ICMPv6 sgrules and it looks like only the ingress rules are affected (based on the fact that these were the only rules that failed to get cleaned up after a `destroy` action).

In https://github.com/tylert/wireguard-terraform/blob/master/vpc_rules/icmp.tf, the following rule definitely experiences the same incorrect behaviour outlined by @sgrimm above...
```
resource "aws_network_acl_rule" "pub_rx_icmpv6" {
  network_acl_id  = data.aws_network_acls.public.ids
  rule_number     = 6102
  egress          = false
  rule_action     = "allow"
  protocol        = 58  # icmpv6
  icmp_type       = -1  # all
  icmp_code       = -1  # all
  ipv6_cidr_block = "::/0"
}
```

**Comment by tylert** [comment]
Also, these extra sgrules are actually missing from the tfstate after the `apply` completes.  The resources did get created in AWS but Terraform thinks they are broken...
```
...
Error: Error finding matching ingress Security Group Rule (sgrule-1566256204) for Group sg-0b27e658da2e3f457



Error: Error finding matching ingress Security Group Rule (sgrule-388306724) for Group sg-02701f916f2fb5059



Error: Error finding matching ingress Security Group Rule (sgrule-1996805917) for Group sg-0f1528eaca7529feb
```

**Comment by kiddom-kq** [comment]
@tylert I was getting hit with this exact issue for TCP, so it's not limited to only ICMP.

As soon as i corrected `::0/0` to `::/0` i no longer had the alternating `Error: Error finding matching ingress Security Group Rule` -> `Error: [WARN] A duplicate Security Group rule was found on` cycle.


My code:

```hcl
variable "lb_ingress_sg_rules" {
  type = list(
    object({
      description      = string,
      type             = string,
      protocol         = string,
      from_port        = number,
      to_port          = number,
      cidr_blocks      = list(string),
      ipv6_cidr_blocks = list(string),
  }))
  description = "list of objects, one object per security group rule, attached to the SG on the lb"
  default = [
    {
      description = "AllowHTTPFromWAN"
      type        = "ingress"
      protocol    = "tcp"
      from_port   = 80
      to_port     = 80
      cidr_blocks = ["0.0.0.0/0"]
     # NOTE: AWS seems to auto correct the erroneous ::0/0 to the correct ::/0 automatically which will break TF.
      ipv6_cidr_blocks = ["::/0"]
    }
  ]
}

locals {
  # Terraform _requires_ either a list of strings or strings as keys pointing to any object type.
  # So we pull the 'name' of each item out and make a string-indexed object
  # See: https://github.com/hashicorp/terraform/issues/23354#issuecomment-553473326
  ##
  lb_ingress_sg_rules = { for item in var.lb_ingress_sg_rules : item.description => item }
}


resource "aws_security_group_rule" "alb" {
  security_group_id = aws_security_group.alb.id

  for_each = local.lb_ingress_sg_rules
  # Add managed by tf to the description
  description = format("%s%s", each.value.description, ";managed by tf")

  type             = each.value.type
  from_port        = each.value.from_port
  to_port          = each.value.to_port
  protocol         = each.value.protocol
  cidr_blocks      = each.value.cidr_blocks
  ipv6_cidr_blocks = each.value.ipv6_cidr_blocks

}

```

I was getting the exact same symptoms with a dynamic/for_each pattern _AND_ a static sg-rule pattern on the latest:

```shell
❯ tf -version
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.25.0
```



I agree with @sgrimm. This is user error and a fatal message along the lines of `did you mean ::/0 ..?` in output would be adequate to prevent this issue.

**Comment by tylert** [comment]
@kiddom-kq well, I guess the difference between the issue you were seeing and the issue I was seeing is that I am only creating a single rule for IPv6/ICMPv6 using the optional `ipv6_cidr_blocks` argument and omitting the `cidr_blocks` one and putting my IPv4 stuff in a different rule (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule).

If you view and run only my https://github.com/tylert/wireguard-terraform/blob/master/vpc_rules/icmp.tf file, you'll get the same behaviour.  It doesn't contain any malformed `::0/0` values and I wasn't seeing this failure happen on any of my TCP rules such as https://github.com/tylert/wireguard-terraform/blob/master/vpc_rules/https.tf.

**Comment by JonRussell00** [comment]
I got the same error if I include a leading zero in my IPv6 address. Like this : 2a03:2800:**0300**::/64

>terraform --version
Terraform v1.0.0
on windows_amd64

**Code extract**:
```
locals {
// DeployHQ details
  deployhq_addresses = [
    //https://www.deployhq.com/support/faq/our-ip-ranges
    "185.22.211.0/24",  // UK
    "152.89.76.0/24",   // US East
    "185.69.56.0/24"    // US West
  ]

  deployhq_addresses_ipv6 = [
    "2a03:2800:0300::/64" // UK
  ]

  deployhq_tcp_ports = [
    "22"   // ssh
  ]
}

// DeployHQ Access
resource "aws_security_group" "deployhq_access" {
  name        = "DeployHQ Management Admin Access"
  description = "Management Access from DeployHQ Servers"
  vpc_id      = aws_vpc.vpc.id
}

resource "aws_security_group_rule" "deployhq_access_ingress_tcp" {
  for_each = toset(local.deployhq_tcp_ports)

  description       = "DeployHQ Access (TCP)"
  cidr_blocks       = local.deployhq_addresses
  ipv6_cidr_blocks  = local.deployhq_addresses_ipv6
  security_group_id = aws_security_group.deployhq_access.id

  type      = "ingress"
  from_port = each.key
  to_port   = each.key
  protocol  = "tcp"
}

```
**Error**:

```
│ Error: Error finding matching ingress Security Group Rule (sgrule-1234567890) for Group sg-1234567890
│
│   with aws_security_group_rule.deployhq_access_ingress_tcp["22"],
│   on security_groups.tf line 203, in resource "aws_security_group_rule" "deployhq_access_ingress_tcp":
│  203: resource "aws_security_group_rule" "deployhq_access_ingress_tcp" {

```

**Solution**: Remove leading zero in IPv6 address
Change:
```
  deployhq_addresses_ipv6 = [
    "2a03:2800:0300::/64" // UK
  ]
```
to
```
  deployhq_addresses_ipv6 = [
    "2a03:2800:300::/64" // UK
  ]
```

and it works fine.

**Comment by irvintim** [comment]
One more failure case, if the IPv6 address has only one empty 16-bit field that is abbreviated with "::" instead of ":0:", so "2001:aaaa:bbbb::cccc:dddd:fe2b:7e9f/128" instead of "2001:aaaa:bbbb:0:cccc:dddd:fe2b:7e9f/128"

> $ terraform -v
> Terraform v0.14.11
> + provider registry.terraform.io/hashicorp/archive v2.2.0
> + provider registry.terraform.io/hashicorp/aws v3.51.0
> + provider registry.terraform.io/hashicorp/null v3.1.0

**Code extract:**
```
variable "ssh_source_ipv6_cidr_blocks" {
  type = list(string)
  default = [
    "2001:aaaa:bbbb::cccc:dddd:fe2b:7e9f/128",
    "2001:aaaa:bbbb::cccc:dddd:fe2d:f8c0/128",
    "2001:aaaa:bbbb:2:cccc:dddd:fea9:fec9/128",
    "2001:aaaa:bbbb:2:cccc:dddd:fe86:aa73/128"
  ]
  description = "My Hosts"
}
resource "aws_security_group" "my_sg" {
  name        = "My-SG"
  description = "Desc"
  vpc_id      = data.aws_vpc.this.id
}

resource "aws_security_group_rule" "inbound_ssh_ipv6" {
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  ipv6_cidr_blocks  = var.ssh_source_ipv6_cidr_blocks
  security_group_id = aws_security_group.my_sg.id
}
```
**Error:**
```
Error: Error finding matching ingress Security Group Rule (sgrule-123891232) for Group sg-05d51afffffffff296

  on main.tf line 133, in resource "aws_security_group_rule" "inbound_ssh_ipv6":
 133: resource "aws_security_group_rule" "inbound_ssh_ipv6" {
```
**Solution:**  Add the missing zero in the addresses, so change:
```
variable "ssh_source_ipv6_cidr_blocks" {
  type = list(string)
  default = [
    "2001:aaaa:bbbb::cccc:dddd:fe2b:7e9f/128",
    "2001:aaaa:bbbb::cccc:dddd:fe2d:f8c0/128",
    "2001:aaaa:bbbb:2:cccc:dddd:fea9:fec9/128",
    "2001:aaaa:bbbb:2:cccc:dddd:fe86:aa73/128"
  ]
  description = "My Hosts"
}
```

to

```
variable "ssh_source_ipv6_cidr_blocks" {
  type = list(string)
  default = [
    "2001:aaaa:bbbb:0:cccc:dddd:fe2b:7e9f/128",
    "2001:aaaa:bbbb:0:cccc:dddd:fe2d:f8c0/128",
    "2001:aaaa:bbbb:2:cccc:dddd:fea9:fec9/128",
    "2001:aaaa:bbbb:2:cccc:dddd:fe86:aa73/128"
  ]
  description = "My Hosts"
}
```

and it works fine.

**Comment by tonyswu** [comment]
This has been a problem for quite some time, hopefully it gains som traction. This is still a problem with the new `aws_vpc_security_group_ingress_rule`, but at least it doesn't fail apply but instead just always flags for changes. For example:

```
resource "aws_vpc_security_group_ingress_rule" "test" {
  security_group_id = aws_security_group.test.id

  cidr_ipv6   = "2600:0c02:1234:1234::/64"
  from_port   = 443
  ip_protocol = "tcp"
  to_port     = 443
}
```

produces the following plan every time:

```
  ~ resource "aws_vpc_security_group_ingress_rule" "test" {
      ~ cidr_ipv6              = "2600:c02:1234:1234::/64" -> "2600:0c02:1234:1234::/64"
        id                            = "sgr-<ID>"
        # (7 unchanged attributes hidden)
    }
```
