### ISSUE TITLE
Unexpected diffs are displayed with terraform plan when sensitive flag is changed

### ISSUE THREAD

**Issue by chroju** [hashicorp/terraform-provider-aws#19010]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
❯ terraform version
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.36.0
```

### Affected Resource(s)

I have seen the same problem with several resources below. I have not been able to identify all the affected resources.

* aws_ssm_parameter
* aws_rds_cluster
* aws_codebuild_source_credential

... etc

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```terraform
variable "sensitive_value" {
  default   = "sensitive"
  type      = string
  sensitive = false
}

resource "aws_ssm_parameter" "foo" {
  name  = "foo"
  type  = "SecureString"
  value = var.sensitive_value
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

 I run `terraform apply` once and then change the `variable.sensitive_value` to `sensitive = true` and run `terraform plan`, I get the following.

```hcl
  # aws_ssm_parameter.foo will be updated in-place
  ~ resource "aws_ssm_parameter" "foo" {
        id        = "foo"
        name      = "foo"
        tags      = {}
      # Warning: this attribute value will be marked as sensitive and will
      # not display in UI output after applying this change
      ~ value     = (sensitive value)
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior

Actually, I get the following. `allowed_pattern` and `description` are optional values. It is not expected that empty strings will be set there.

```hcl
  # aws_ssm_parameter.foo will be updated in-place
  ~ resource "aws_ssm_parameter" "foo" {
      + allowed_pattern = ""
      + description     = ""
        id              = "foo"
        name            = "foo"
        tags            = {}
      # Warning: this attribute value will be marked as sensitive and will
      # not display in UI output after applying this change
      ~ value           = (sensitive value)
        # (6 unchanged attributes hidden)
    }
```

Also, if you change from `sensitive = true` to `false`, `allowed_pattern` and `description` will be set back to null.

```hcl
  # aws_ssm_parameter.foo will be updated in-place
  ~ resource "aws_ssm_parameter" "foo" {
      - allowed_pattern = "" -> null
      - description     = "" -> null
        id              = "foo"
        name            = "foo"
        tags            = {}
      # Warning: this attribute value will no longer be marked as sensitive
      # after applying this change
      ~ value           = (sensitive value)
        # (6 unchanged attributes hidden)
    }
```

### Steps to Reproduce

1. `terraform init`
1. `terraform apply -auto-approve`
1. Rewrite the configuration (`sensitive = true`).
1. `terraform plan`

### Important Factoids

Nothing.

### References

I'm not sure if this is a problem with terraform itself or with the aws provider. So, the same issue has also been submitted to hashicorp/terraform#28454

**Comment by chroju** [comment]
Close this issue because this has been resolved by hashicorp/terraform#28454 .

**Comment by bondezbond** [comment]
So I'm having a similar issue and from my understanding from hashicorp/terraform#28454. Is that we it'll show up when we do some other changes to the ssm parameter? But I'm seeing this show up after running a plan, apply and another plan!

Still shows the same resources being changed for allowed_pattern & description. When nothing else has changed. Is that supposed to be the case?
