### ISSUE TITLE
`update_default_version` argument for the aws_launch_template should be more idempotent

### ISSUE THREAD

**Issue by haidangwa** [hashicorp/terraform-provider-aws#19411]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When `update_default_version = true` in the `aws_launch_template` resource, I am seeing that terraform indicates a change for every terraform apply even if the latest version of the launch template doesn't change in the terraform apply. This adds unnecessary output to the terraform run, as well as possible unnecessary API calls to AWS.

I would like to see terraform report changes to the aws_launch_template only if the latest version of the launch template is actually changing and not on every terraform plan/apply.

### New or Affected Resource(s)

* aws_launch_template

### Affected versions
I've found this problem on different versions of terraform, as follows:

```
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

```
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Potential Terraform Configuration

```hcl
resource "aws_launch_template" "servers" {
    description = "example launch template"
    image_id = "ami-xxxxxxx"
    update_default_version = true
    name = "Example Launch template for servers"
}

```

### Results
The launch template has no changes, not even the latest_version changes, but terraform shows that an update will occur.

```
  # aws_launch_template.servers will be updated in-place
  ~ resource "aws_launch_template" "servers" {
      ~ default_version         = 261 -> (known after apply)
        id                      = "lt-0eeed4f34732d2793"
      ~ latest_version          = 261 -> (known after apply)
        name                    = "Example Launch template for servers"
        # (11 unchanged attributes hidden)

        # (6 unchanged blocks hidden)
    }
```

**Comment by haidangwa** [comment]
@YakDriver hmmm...I was on 0.14.11. Maybe I need to plan an upgrade to 0.15

**Comment by haidangwa** [comment]
@YakDriver I've run through 3 consecutive `terraform apply` on my dev infrastructure, and all three times terraform said it changes the same resources. I'm using terraform 0.14.11 and the aws provider 3.42.0. It's not 0.15.4 yet, but we're not quite ready to move there. This seems like a provider issue, so at least we're on the current AWS provider version.

```Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

**Comment by haidangwa** [comment]
There are multiple launch template resources, but they're all like this output.

```
  ~ resource "aws_launch_template" "license_server" {
      ~ default_version         = 262 -> (known after apply)
        id                      = "lt-0450c7b32e4ed408e"
      ~ latest_version          = 262 -> (known after apply)
        name                    = "license-etech-us-east-1-dev"
        tags                    = {
            "splunk_org" = "etech"
        }
        # (11 unchanged attributes hidden)




        # (6 unchanged blocks hidden)
    }
```

**Comment by haidangwa** [comment]
@YakDriver I think I just stumbled upon the actual bug. It's not in the `default_version` at all, unfortunately. When I set that to false, I'm now seeing the same launch_template resources flagged for update due to the `latest_version`.

With `update_default_version = false`

```
    ~ resource "aws_launch_template" "license_server" {
      ~ default_version         = 262 -> (known after apply)
        id                      = "lt-0450c7b32e4ed408e"
      ~ latest_version          = 262 -> (known after apply)
        name                    = "license-etech-us-east-1-dev"
        tags                    = {
            "splunk_org" = "etech"
        }
        # (11 unchanged attributes hidden)




        # (6 unchanged blocks hidden)
    }

```

**Comment by stealthHat** [comment]
im having the same issue using terraform 0.15.4 and aws provider 3.42.0

**Comment by haidangwa** [comment]
A quick update: @YakDriver I upgraded to terraform 0.15.4 and aws provider 3.42.0, but the problem is still there for me. I have a couple of submodules that are called by my root module -- could that be the difference to what you saw in your repro case?

**Comment by m13t** [comment]
I can confirm the same here too on Terraform v14 and v15. This issue was introduced as part of the AWS provider v3.38.0 and is present in every subsequent version after this. v3.37.0 is the last good version.

**Comment by stealthHat** [comment]
any update? this still happens in the latest versions of aws and terraform.

**Comment by WheresWardy** [comment]
In the places we had this issue we also had some slightly odd behaviour with `ignore_changes` going on - we fixed it by either removing the lifecycle completely if we didn't need it, or ensuring both `default_version` and `latest_version` were ignored if we were keeping the lifecycle around (we have `update_default_version = true` everywhere so this makes sure the default version is updated even if we ignore it).

**Comment by zhelding** [comment]
Hi @haidangwa. I'm investigating this issue and am likewise unable to reproduce.

I have tried both making use of a simple config like @YakDriver's [above](https://github.com/hashicorp/terraform-provider-aws/issues/19411#issuecomment-846068910) as well as a more complex config -- i.e. a launch template based on a custom AMI used for the nodes of an EKS cluster, as per issue terraform-aws-modules/terraform-aws-eks#1597.

In both cases, I am able to run a successful `terraform apply`, and further runs fail to produce any diffs.

@haidangwa: are you able to provide a more comprehensive version of your failing config? Likewise, if other commenters are able to share their failing configs, that would be extremely helpful!

**Comment by gdavison** [comment]
@haidangwa and others seeing this error, in addition to the config requested by @zhelding, can you also include Terraform debug logs, please? That can often help with locating problems. See https://www.terraform.io/docs/internals/debugging.html for instructions.

**Comment by mvoitko** [comment]
I am also facing the issue

**Comment by hizeph** [comment]
Hi @zhelding, I know it's been some time since this issue was opened, but It's still occurring.

I tested on provider 4.19 and 3.64. This behavior seems to happen when there is an `ignore_changes` block on the launch template (not sure if that is the only trigger).

Here is my launch template example:
```
resource "aws_launch_template" "default" {
  name_prefix            = "default-lt-"
  description            = "Default Launch-Template"
  update_default_version = true
  image_id               = ""
  key_name               = ""

  block_device_mappings {
    device_name = "/dev/xvda"
    ebs {
      volume_size           = 20
      volume_type           = "gp2"
      delete_on_termination = true
      encrypted             = true
      kms_key_id            = ""
    }
  }

  block_device_mappings {
    device_name = "/dev/xvdb"

    ebs {
      volume_size           = 100
      volume_type           = "gp2"
      delete_on_termination = true
      encrypted             = true
      kms_key_id            = ""
    }
  }

  monitoring {
    enabled = true
  }

  network_interfaces {
    associate_public_ip_address = false
    delete_on_termination       = true
    security_groups             = [""]
  }

  user_data = base64encode("")

  tag_specifications {
    resource_type = "instance"

    tags = {
      CustomTag = "eks-bottlerocket-nodes"
    }
  }
  tag_specifications {
    resource_type = "volume"

    tags = {
      CustomTag = "eks-bottlerocket-nodes"
    }
  }
  tags = {
    CustomTag = "eks-bottlerocket-nodes"
  }

  lifecycle {
    create_before_destroy = true
    ignore_changes = [
      name_prefix
    ]
  }
}
```

Removing the code below stops the unnecessary updates from happening.
```
ignore_changes = [
  name_prefix
]
```

**Comment by d3vpasha** [comment]
I still have this issue, can someone look into it ?

**Comment by jv4n5e** [comment]
I face this issue when running terraform plan/apply from a different user, although no changes have been made in the code. My scenario is as follows:

- The issue does not occur when terraform apply is issued by user **A**, and once changes take effect, user **A** executes terraform plan/apply.
- The issue does not occur when terraform apply is issued by user **B**, and once changes take effect, user **B** executes terraform plan/apply.
- The issue occurs when terraform apply is issued by user **A**, and once changes take effect, user **B** executes terraform plan/apply.
- The issue occurs when terraform apply is issued by user **A**, and once changes take effect, user **A** executes terraform plan/apply.

I am using Terraform v1.5.7 on windows_amd64. My launch template is as follows:
```
resource "aws_launch_template" "worker-nodes-launch-template" {
  image_id                  = data.aws_ssm_parameter.eks-worker-ami.value
  instance_type             = "r5a.xlarge"
  name                      = "${local.eks_cluster_name}-worker-nodes-launch-template"
  ebs_optimized             = true
  update_default_version    = true
  
  block_device_mappings {
    device_name = "/dev/xvda"

    ebs {
      volume_size = 100
      volume_type = "gp3"
      iops        = 3000
    }
  }

  lifecycle {
    create_before_destroy = true
  }

  network_interfaces {
    security_groups = [aws_eks_cluster.eks.vpc_config[0].cluster_security_group_id] 
  }

  depends_on = [aws_eks_cluster.eks]

  user_data = base64encode(templatefile("userdata.tpl", { CLUSTER_NAME = aws_eks_cluster.eks.name, B64_CLUSTER_CA = aws_eks_cluster.eks.certificate_authority[0].data, API_SERVER_URL = aws_eks_cluster.eks.endpoint }))
}

data "aws_launch_template" "worker-nodes-launch-template" {
  name = aws_launch_template.worker-nodes-launch-template.name

  depends_on = [aws_launch_template.worker-nodes-launch-template]
}
```

**Comment by alencar** [comment]
I had the same issue with a `lifecycle { ignore_changes = [ image_id ] }`. By removing `ignore_changes` from `lifecycle {}` the issue _dissapeared_

```$ terraform --version
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v4.67.0
...
```

**Comment by mshoeb** [comment]
Encountering this and adding lifecycle { ignore_changes = [ latest_version ]} generated a warning without resolving the issue.

`│ Adding an attribute name to ignore_changes tells Terraform to ignore future changes to the argument in configuration after the object has been created, retaining the value
│ originally configured.
│ 
│ The attribute latest_version is decided by the provider alone and therefore there can be no configured value to compare with. Including this attribute in ignore_changes has no
│ effect. Remove the attribute from ignore_changes to quiet this warning.`

Terraform provider version

`Terraform v1.5.3
on darwin_amd64
provider registry.terraform.io/hashicorp/aws v5.25.0`

**Comment by MattiaEffendi** [comment]
Hi, we are still facing the issue and can't seem to find a workaround. 
We do need to have the `ignore_change` lifecycle policy so removing it doesn't seem to be an option for us. 

Can someone suggest a workaround or definite fix for this bug? Thanks

**Comment by jar-b** [comment]
Hello everyone - In reading through the history of this issue, two separate concerns have been reported:

1. Setting `update_default_version` to `true` causes persistent differences (original issue body).
1. Using an `ignore_changes` lifecycle block causes persistent differences (subsequent comments).

In both cases I've been unable to reproduce the reported behavior with the latest versions of Terraform and the AWS provider. Details of my attempted reproduction are included below. As my reproduction attempt, along with previous attempts from other maintainers, have not proven successful we're planning to leave this open for two more weeks to allow for community feedback before closing this issue as fixed upstream.

If you believe an ongoing issue that we haven't covered in our reproduction is still occuring, please include a minimal configuration and the relevant `terraform plan/apply` output below. Thanks!

## Reproduction 1 - `update_default_version` set to `true`

This is the concern reported in the original issue body.

### Configuration

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {}

data "aws_ami" "amzn2-ami-minimal-hvm-ebs" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["amzn2-ami-minimal-hvm-*"]
  }

  filter {
    name   = "root-device-type"
    values = ["ebs"]
  }
}

resource "aws_launch_template" "servers" {
  description            = "jb-test"
  image_id               = data.aws_ami.amzn2-ami-minimal-hvm-ebs.id
  update_default_version = true
  name                   = "jb-test"
}
```

### Results

```console
% terraform -version
Terraform v1.8.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.45.0
```

```console
% terraform apply -auto-approve
data.aws_ami.amzn2-ami-minimal-hvm-ebs: Reading...
data.aws_ami.amzn2-ami-minimal-hvm-ebs: Read complete after 0s [id=ami-01e7fe416e850d2fb]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_launch_template.servers will be created
  + resource "aws_launch_template" "servers" {
      + arn                    = (known after apply)
      + default_version        = (known after apply)
      + description            = "jb-test"
      + id                     = (known after apply)
      + image_id               = "ami-01e7fe416e850d2fb"
      + latest_version         = (known after apply)
      + name                   = "jb-test"
      + name_prefix            = (known after apply)
      + tags_all               = (known after apply)
      + update_default_version = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.
aws_launch_template.servers: Creating...
aws_launch_template.servers: Creation complete after 1s [id=lt-02bb587e6313e9335]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

```console
% terraform plan
data.aws_ami.amzn2-ami-minimal-hvm-ebs: Reading...
data.aws_ami.amzn2-ami-minimal-hvm-ebs: Read complete after 1s [id=ami-01e7fe416e850d2fb]
aws_launch_template.servers: Refreshing state... [id=lt-02bb587e6313e9335]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

## Reproduction 2 - `ignore_changes` lifecycle block

This is the concern reported in multiple subsequent comments. Specifically, the tested configuration was derived from [this comment](https://github.com/hashicorp/terraform-provider-aws/issues/19411#issuecomment-1163111200).

### Configuration

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {}

resource "aws_launch_template" "default" {
  name_prefix            = "default-lt-"
  description            = "Default Launch-Template"
  update_default_version = true

  block_device_mappings {
    device_name = "/dev/xvda"
    ebs {
      volume_size           = 20
      volume_type           = "gp2"
      delete_on_termination = true
      encrypted             = true
    }
  }

  lifecycle {
    create_before_destroy = true
    ignore_changes = [
      name_prefix
    ]
  }
}

```

### Results

```console
% terraform -version
Terraform v1.8.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.45.0
```

```console
% terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_launch_template.default will be created
  + resource "aws_launch_template" "default" {
      + arn                    = (known after apply)
      + default_version        = (known after apply)
      + description            = "Default Launch-Template"
      + id                     = (known after apply)
      + latest_version         = (known after apply)
      + name                   = (known after apply)
      + name_prefix            = "default-lt-"
      + tags_all               = (known after apply)
      + update_default_version = true

      + block_device_mappings {
          + device_name = "/dev/xvda"

          + ebs {
              + delete_on_termination = "true"
              + encrypted             = "true"
              + iops                  = (known after apply)
              + throughput            = (known after apply)
              + volume_size           = 20
              + volume_type           = "gp2"
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
aws_launch_template.default: Creating...
aws_launch_template.default: Creation complete after 1s [id=lt-0a9ce3ab6b2a8fa0e]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

To confirm changes are properly ignored, update the value of `name_prefix`:

```console
% cat main.tf | rg "name_prefix.*="
  name_prefix            = "default-lt-updated-"
```

```console
% terraform plan
aws_launch_template.default: Refreshing state... [id=lt-0a9ce3ab6b2a8fa0e]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

## Summary

Absent any concerns with these reproductions, we'll close this issue as fixed upstream on 2024-04-30.

**Comment by jar-b** [comment]
Since we have not received any responses, we'll be closing this issue today.

If you experience a related issue that was not covered by the reproductions above, please open a new issue with a minimal configuration and link to this one. Thanks!
