### ISSUE TITLE
Provider produced inconsistent final plan / an invalid new value for .tags_all

### ISSUE THREAD

**Issue by chgasparoto** [hashicorp/terraform-provider-aws#19583]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

### Affected Resource(s)

* aws_vpc
* aws_subnet

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

# https://github.com/chgasparoto/youtube-cleber-gasparoto/tree/main/0002-terraform-lambda-layer

terraform {
  required_version = "0.15.4"
}

provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile

  default_tags {
    tags = {
      Project   = "Lambda Layers with Terraform"
      CreatedAt = formatdate("YYYY-MM-DD", timestamp())
      ManagedBy = "Terraform"
      Owner     = "Cleber Gasparoto"
    }
  }
}
resource "aws_vpc" "example" {
  cidr_block = "10.1.0.0/16"
  tags = {
    Name = "my-vpc-resource"
  }
}
resource "aws_subnet" "example" {
  cidr_block = "10.1.1.0/24"
  vpc_id     = aws_vpc.example.id
  tags = {
    Name = "my-subnet-resource"
  }
}
```

### Debug Output

```
aws_iam_role.cat_api_lambda: Modifications complete after 1s [id=cat-api-lambda-role]
aws_lambda_function.cat_api: Modifying... [id=cat_api]
aws_lambda_function.cat_api: Modifications complete after 0s [id=cat_api]
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_vpc.example to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "CreatedAt" has
│ appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_vpc.example to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "ManagedBy" has
│ appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_vpc.example to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Owner" has
│ appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_vpc.example to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Project" has
│ appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```
### Expected Behavior

VPC and Network created with default tags successfully

### Actual Behavior

VPC and Network are not created

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by anGie44** [comment]
Thank you for reporting this issue @chgasparoto ! This seems related to the the apply-time computed tag, `CreatedAt` , unfortunately. I'm seeing the `terraform plan` isn't correctly calculating the `tags_all` attribute as it technically should either include all the possible tags (default_tags + resource tags) or suggest the map is `known after apply`:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_subnet.example will be created
  + resource "aws_subnet" "example" {
      + arn                             = (known after apply)
      + assign_ipv6_address_on_creation = false
      + availability_zone               = (known after apply)
      + availability_zone_id            = (known after apply)
      + cidr_block                      = "10.1.1.0/24"
      + id                              = (known after apply)
      + ipv6_cidr_block_association_id  = (known after apply)
      + map_public_ip_on_launch         = false
      + owner_id                        = (known after apply)
      + tags                            = {
          + "Name" = "my-subnet-resource"
        }
      + tags_all                        = {
          + "Name" = "my-subnet-resource"
        }
      + vpc_id                          = (known after apply)
    }

  # aws_vpc.example will be created
  + resource "aws_vpc" "example" {
      + arn                              = (known after apply)
      + assign_generated_ipv6_cidr_block = false
      + cidr_block                       = "10.1.0.0/16"
      + default_network_acl_id           = (known after apply)
      + default_route_table_id           = (known after apply)
      + default_security_group_id        = (known after apply)
      + dhcp_options_id                  = (known after apply)
      + enable_classiclink               = (known after apply)
      + enable_classiclink_dns_support   = (known after apply)
      + enable_dns_hostnames             = (known after apply)
      + enable_dns_support               = true
      + id                               = (known after apply)
      + instance_tenancy                 = "default"
      + ipv6_association_id              = (known after apply)
      + ipv6_cidr_block                  = (known after apply)
      + main_route_table_id              = (known after apply)
      + owner_id                         = (known after apply)
      + tags                             = {
          + "Name" = "my-vpc-resource"
        }
      + tags_all                         = {
          + "Name" = "my-vpc-resource"
        }
    }
```

**Comment by matiu2** [comment]
If anyone figures out a work around in the meantime, please paste it here.

**Comment by matiu2** [comment]
My work around is:
1. Comment out the default_tags block
2. Build
3. Uncomment the default_tags block
4. re-apply

**Comment by anGie44** [comment]
Hi @matiu2 , thank you for following up on this issue! I don't believe there is a current workaround when using an apply-time Computed key/value pair like `CreatedAt = timestamp()` . I'm curious, in the workaround you've provided, were you also working with dynamic tag values in the `default_tags.tags` block?

Following the steps you've provided, if I'm using a timestamp value in the `default_tags` block, the final `apply` will not produce any modifications to the resource unfortunately as terraform won't detect the changes in the `default_tags` block even though it has been uncommented. The reason being that internally, the `default_tags` block is read as an empty map during run time (as it's marked as Computed just by having that one `timestamp()` tag for example), and merging the resource tags (in the example, `Name="my-subnet-resource"` etc.) on top of that empty map leaves us with no diff as it represents the original map.

**Comment by ashraf133** [comment]
Hello,
Same problem for me while addind a tag "Name" which is not a part of default tags :

**RESOURCE :**
resource "aws_ami_copy" "server_encrypted" {
  name              = format("encrypted-server-ami.%s", local.timestamp_sanitized)
  description       = format("server (encrypted) created on : %s", local.timestamp_sanitized)
  source_ami_id     = data.aws_ami.latest_server.id
  source_ami_region = var.region
  encrypted         = true
  kms_key_id        = var.kms_key_id

  tags = {
    Name      = format("encrypted-server-ami.%s", local.timestamp_sanitized)
  }
}

**PROVIDER :**
provider "aws" {
  region = var.region
 default_tags {
  tags = {
   Owner     = var.Owner
   Stage     = var.Stage
   Project   = var.Project
   ManagedBy = var.ManagedBy
   Region    = var.region
  }
}
}


**ERROR**
Error: Provider produced inconsistent final plan
When expanding the plan for aws_ami_copy.zabbix_server_encrypted to include
new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.tags_all: new element "Name" has appeared.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Regards

**Comment by Marinaburkhardt** [comment]
Hi, same error here when adding an extra "Name" tag to a S3 bucket.

## Used versions

- terraform_version: 0.14.9
- provider: registry.terraform.io/hashicorp/aws v3.39.0

## Expected Behavior
S3 bucket created with default tags + customized tags successfully

## Actual Behavior
S3 bucket is not created

## Code snippet

```terraform
provider "aws" {
  profile = var.aws_profile
  region  = var.aws_region

  default_tags {
    tags = {
      Created_by = "Terraform"
      Project    = "AWS_demo_fullstack_devops"
    }
  }
}

resource "aws_s3_bucket" "s3_bucket" {
  bucket        = var.bucket_name
  acl           = "private"
  force_destroy = true
  tags = {
    Name = var.bucket_name
  }
}
```

## Plan output

```
  # module.s3_assets.aws_s3_bucket.s3_bucket will be created
  + resource "aws_s3_bucket" "s3_bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = (known after apply)
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = true
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = (known after apply)
      + tags_all                    = {
          + "Created_by" = "Terraform"
          + "Project"    = "AWS_demo_fullstack_devops"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }
```

## Error output (during apply)

```
Error: Provider produced inconsistent final plan

When expanding the plan for module.s3_assets.aws_s3_bucket.s3_bucket to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.tags_all: new element "Name" has appeared.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Regards,
Mari

**Comment by anGie44** [comment]
Thank you for providing additional context @ashraf133 and @Marinaburkhardt ! In both cases seems having a resource `tags` set with a `var` is not not being picked (by `tags_all`) 😞. Will add this to the investigation 👍

**Comment by anniehedgpeth** [comment]
I just ran into the same issue [here](https://github.com/hashicorp/terraform-aws-terraform-enterprise/runs/2805990181?check_suite_focus=true#step:9:2099) with config from [this](https://github.com/hashicorp/terraform-aws-terraform-enterprise/pull/183) pull request. 
Terraform v0.14.9
hashicorp/aws v3.45.0

**Comment by Marinaburkhardt** [comment]
Error seems to be fixed, I retried the deployment and now it worked. But the output doesn't show up as expected:

## Apply output:

```
# module.s3_assets.aws_s3_bucket.s3_bucket will be created
  + resource "aws_s3_bucket" "s3_bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "assets-eu-central-1-4dc5"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = true
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = {
          + "Name" = "assets-eu-central-1-4dc5"
        }
      + tags_all                    = {
          + "Created_by" = "Terraform"
          + "Name"       = "assets-eu-central-1-4dc5"
          + "Project"    = "AWS_demo_fullstack_devops"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }
```

I think the "Name" tag shouldn't be listed under `tags_all` und just under `tags` instead, since it's just a resource tag (see the code snippet used above in my previous comment).

Hope that helps 😄

**Comment by sorengraungaard** [comment]
@Marinaburkhardt the one resource type I don't have this problem with is S3 buckets, lots of other resource have this problem for me (RDS, Route53, Elasticsearch, cognito, and others)

**Comment by share-me** [comment]
Same for me, how to upvote for this issue? 

How to Fix: just launch again
(but this solution doesn't fit for a Jenkins/Gitlab chain)


```
module.mq04.aws_mq_broker.mq: Creation complete after 9m54s [id=b-581xxx7d-xxxx-xxxx-xxxx-14547xx12345]

Error: Provider produced inconsistent final plan

When expanding the plan for module.rds01.aws_db_subnet_group.postgresql to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.tags_all: new element "Name" has appeared.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

```
$ terraform version
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.46.0
```

**Comment by rtoma** [comment]
Another case where this bug hurts, using the ALB module https://registry.terraform.io/modules/terraform-aws-modules/alb/aws/latest

```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.xxxxxxxx[0].module.alb.aws_lb_listener.frontend_https[0]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.tags_all: new element "Name" has appeared.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

From plan. Note the code attempts to add a Name tag to `tags` causing the 
```
  # module.xxxxxxx[0].module.alb.aws_lb_listener.frontend_https[0] will be created
  + resource "aws_lb_listener" "frontend_https" {
      + alpn_policy       = (known after apply)
      + arn               = (known after apply)
      + certificate_arn   = (known after apply)
      + id                = (known after apply)
      + load_balancer_arn = (known after apply)
      + port              = 443
      + protocol          = (known after apply)
      + ssl_policy        = (known after apply)
      + tags              = (known after apply)
      + tags_all          = {
                       (all provider level tags here)
        }

      + default_action {
          + order            = (known after apply)
          + target_group_arn = (known after apply)
          + type             = (known after apply)
        }
      + default_action {
          + order            = (known after apply)
          + target_group_arn = (known after apply)
          + type             = (known after apply)
        }
    }
```

My versions:
```
$ tf version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.40.0
````

**Comment by tuxtek** [comment]
I ran into this with the AWS EKS module as well.

```
Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.eks.aws_security_group.workers[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an
│ invalid new value for .tags_all["Name"]: was cty.StringVal("Shawn EKS Testing"), but now cty.StringVal("Shawn EKS Testing-GEyDNwpt-eks_worker_sg").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.eks.aws_security_group.workers[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an
│ invalid new value for .tags_all: new element "kubernetes.io/cluster/Shawn EKS Testing-GEyDNwpt" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.eks.aws_security_group.cluster[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an
│ invalid new value for .tags_all["Name"]: was cty.StringVal("Shawn EKS Testing"), but now cty.StringVal("Shawn EKS Testing-GEyDNwpt-eks_cluster_sg").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: invalid value for name_prefix (must match [\w+=,.@-])
│ 
│   with module.eks.aws_iam_role.cluster[0],
│   on .terraform/modules/eks/cluster.tf line 121, in resource "aws_iam_role" "cluster":
│  121:   name_prefix           = var.cluster_name
│ 
╵
╷
│ Error: invalid value for name_prefix (must match [\w+=,.@-])
│ 
│   with module.eks.aws_iam_policy.cluster_elb_sl_role_creation[0],
│   on .terraform/modules/eks/cluster.tf line 167, in resource "aws_iam_policy" "cluster_elb_sl_role_creation":
│  167:   name_prefix = "${var.cluster_name}-elb-sl-role-creation"
│ 
```

For my own instance of this, I was able to resolve it by removing the space in the tag.Name value I was using and replace with `-` instead. Ideally, it would have been good to see this warning in the plan. While resolved, I am sharing case this applies to any other use cases.

My Version:
```$ terraform --version
Terraform v1.0.1
```

**Comment by ssukumar-conga** [comment]
declare the default tags as local variable 
locals {
common_tags =  {
      createdby   = "me"
      createdon   = formatdate("MM/DD/YYYY", timestamp())
      purpose     = "test"
      environment = "dev"
      buildby     = "automation"
    } 
}
and in each resource where u must be adding the name append this also
tags = { for k, v in merge({ "Name" = "test-vpc-1"},local.common_tags) : k => v }

**Comment by ssukumar-conga** [comment]
###

**Comment by sneha43sweety** [comment]
declare the default tags as local variable
locals {
common_tags = {
createdby = "me"
createdon = formatdate("MM/DD/YYYY", timestamp())
purpose = "test"
environment = "dev"
buildby = "automation"
}
}
and in each resource where u must be adding the name append this also
tags = { for k, v in merge({ "Name" = "test-vpc-1"},local.common_tags) : k => v }

**Comment by jgeurts** [comment]
I ran into this with the rds cluster. Terraform v1.0.2 and aws provider v3.50.0:

```terraform
resource "aws_rds_cluster" "clone" {
  ...

  tags = {
    Name    = "clone"
    Created = timestamp()
  }
}
```

```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.db_clone.aws_rds_cluster.clone to include new 
values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.tags_all: new element "Name" has appeared.

This is a bug in the provider, which should be reported in the provider's
own issue tracker.
```

**Comment by sneha43sweety** [comment]
> I ran into this with the rds cluster resource. Terraform v1.0.2 and aws provider v3.50.0:
> 
> ```terraform
> provider "aws" {
>   region              = var.aws_region
>   allowed_account_ids = [var.aws_account_id]
> 
>   default_tags {
>     tags = {
>       Terraform = "true"
>     }
>   }
> }
> 
> resource "aws_rds_cluster" "clone" {
>   ...
> 
>   tags = {
>     Name    = "clone"
>     Created = timestamp()
>   }
> }
> ```
> 
> ```
> Error: Provider produced inconsistent final plan
> 
> When expanding the plan for
> module.db_clone.aws_rds_cluster.clone to include new 
> values learned so far during apply, provider
> "registry.terraform.io/hashicorp/aws" produced an invalid new value for
> .tags_all: new element "Name" has appeared.
> 
> This is a bug in the provider, which should be reported in the provider's
> own issue tracker.
> ```

Please remove the default tags ad put that tag in local variable
and with each resource merge the local variable along with resource tag. Its one of the workaround

**Comment by sarangk39** [comment]
We are upgrading to Terraform v0.12.31 and AWS provider v3.38.0

Our current terraform configuration looks like this -

`provider aws {
version = “3.38.0”
}

locals {
common_tags = {
Source = var.source_tag
Team = var.owner_tag
Lifecycle = var.lifecycle_tag
Project = var.project_tag
EnvironmentType = var.environment_type_tag
Environment = var.environment_id
Contact = var.contact_tag
}
}

resource aws_dynamodb_table xyz {
tags = local.common_tags
}`

### Code output - 

aws_dynamodb_table.xyz will be updated in-place
resource "aws_dynamodb_table" "xyz" {
tags= {} (known after apply)
tags_all = {}


### When we run the terraform files, getting below error -

_Provider produced inconsistent final plan
When expanding the plan for aws_dynamodb_table.xyz to
include new values learned so far during apply, provider
“registry.terraform.io/-/aws” produced an invalid new value for .tags_all: new element “Contact” has appeared.
This is a bug in the provider, which should be reported in the provider’s own issue tracker._

The same configuration works when we manually delete the existing Dynamo DB table and re-run the files. But we want to avoid getting this error in first place. What changes do we need to make in our files to avoid this error ?

### Code output (when tables are deleted manually) - 

aws_dynamodb_table.xyz will be created
resource "aws_dynamodb_table" "xyz" {
tags            = (known after apply)
tags_all        = (known after apply)

**Comment by inhumantsar** [comment]
I ran into the same error with the `aws_security_group` resource in the `terraform-aws-modules/security-group/aws` module: https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/main.tf#L11-L25

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.development_public_alb_sg.aws_security_group.this_name_prefix[0] 
to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an
│ invalid new value for .tags_all: new element "Name" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

```
❯ terraform --version
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.44.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

I was able to work around the error by re-running `terraform apply`.

**Comment by cmd-werner** [comment]
Sam issue for me

**Comment by kihom-77** [comment]
To avoid this I use a variable that contains the timestamp which is set just prior to the apply.

`export TF_VAR_TIMESTAMP="$( date --rfc-3339=seconds )"`

```

variable "TIMESTAMP" { default = "1900-01-01 00:00:00+02:00" }

provider "aws" {
  region = var.AWS_REGION
  default_tags {
    tags = {
      "tf:apply" = var.TIMESTAMP  
    }
  }
}
```

This work with `Terraform v0.13.7`

**Comment by dmccaffery** [comment]
We have also hit this issue in a slightly different form whereas a depends_on on the resource will cause a diff in tags vs tags_all at plan time even though all of the tags are statically defined. Works completely fine when dependencies are automatically determined; kinda weird.

**Comment by JamesMcOrmond** [comment]
still confirmed with Terraform 1.0.10 and aws provider 3.64.x..   

if I have a dynamic (in my case a random id) as part of default_tags set in the provider configs, my apply run is very inconsistent.
its the same 'new element has appeared" style messages as above.

**Comment by lorengordon** [comment]
> Hi @matiu2 , thank you for following up on this issue! I don't believe there is a current workaround when using an apply-time Computed key/value pair like `CreatedAt = timestamp()` . I'm curious, in the workaround you've provided, were you also working with dynamic tag values in the `default_tags.tags` block?
> 
> Following the steps you've provided, if I'm using a timestamp value in the `default_tags` block, the final `apply` will not produce any modifications to the resource unfortunately as terraform won't detect the changes in the `default_tags` block even though it has been uncommented. The reason being that internally, the `default_tags` block is read as an empty map during run time (as it's marked as Computed just by having that one `timestamp()` tag for example), and merging the resource tags (in the example, `Name="my-subnet-resource"` etc.) on top of that empty map leaves us with no diff as it represents the original map.

My case is similar to this, but instead of a computed value using a function like `timestamp()`, I'm passing a resource ID from another resource in one of the tags. Originally did this as a method of ordering an implicit dependency, but then I kinda liked having the information about the relationship in the tag. But looking like I'll need to just use `depends_on` instead.

**Comment by thenom** [comment]
TF: v1.0.11
AWS: 3.66.0

I am having this issue with EBS volumes.  Default_tags set at the parent TF provider which is picked up by the TF module and the ebs_vol resource in the module adds the missing tags:

```
provider "aws" {
  region = "eu-west-1"
  default_tags {
    tags = module.tags.tags
  }
}
```

in elasticsearch TF module:
```
resource "aws_ebs_volume" "data-nodes-vols" {
  tags = merge(var.default_tags,
    tomap({
      "Name"       = "${var.cluster_name}_es_data_vol_${count.index % local.data_node_counts}",
      "NodeId"     = count.index % local.data_node_counts,
      "AsgEbsUuid" = random_uuid.asg_ebs_instance_uuids[count.index % local.data_node_counts].result
      "Device"     = lookup(element(var.es_data_block_device, floor(count.index / local.data_node_counts)), "device_name")
    })
  )
```

Results in:

> Error: Provider produced inconsistent final plan
>
> When expanding the plan for
> module.elasticsearch.aws_ebs_volume.data-nodes-vols[0] to include new
> values learned so far during apply, provider
> "registry.terraform.io/hashicorp/aws" produced an invalid new value for
> .tags_all: new element "AsgEbsUuid" has appeared.
> 
> This is a bug in the provider, which should be reported in the provider's
> own issue tracker.

For every additional tag added (Name, NodeId, AsgEbsUuid, Device)

Weirdly, this is not happening for every parent terraform that is using this elasticsearch TF module even though i cannot find any difference in the tags passed.

**Comment by ssukumar-conga** [comment]
provider "aws" {
  region = "eu-west-1"
}

declare the default tags as local variable
locals {
common_tags = {
tags = module.tags.tags
}
}
resource "aws_ebs_volume" "data-nodes-vols" {
  tags = merge(local.common_tags,
    tomap({
      "Name"       = "${var.cluster_name}_es_data_vol_${count.index % local.data_node_counts}",
      "NodeId"     = count.index % local.data_node_counts,
      "AsgEbsUuid" = random_uuid.asg_ebs_instance_uuids[count.index % local.data_node_counts].result
      "Device"     = lookup(element(var.es_data_block_device, floor(count.index / local.data_node_counts)), "device_name")
    })
  )

try this way

**Comment by thenom** [comment]
Just a note on my extra edit on my last post.  Its seems this was a red herring as the first deploy has this issue but the 2nd attempt works fine.  This is replicable.

**Comment by lkolchin** [comment]
This is not a red herring.
Hitting the same issue when using 
```
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
  default_tags {
    tags = local.default_tags_us_east_1
  }
}
```
and 
```
resource "aws_ebs_volume" "vol_ebs_useast1_az" {
  provider = aws.us-east-1
  availability_zone = "us-east-1a"
  size              = 10
  tags = {
    somekey = "somevalue"
  }
}
```

Once the following is commented out:
```
  tags = {
    somekey = "somevalue"
  }
  ```

I stop getting:
```
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_ebs_volume.vol_ebs_useast1_az to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an
│ invalid new value for .tags_all: new element "app" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by lkolchin** [comment]
Found the problem.
It bombs out when one of your tags is equal to timestamp() (or formatdate("....", timestamp()).
But it works fine with other dynamic values (like the ones derived from `data "aws_caller_identity" "current" {}` for example).
Seems to be a bug :(

**Comment by fitchtech** [comment]
This also occurs when running a plan for a module that uses the lookup function for the values of tags. The lookup function causes various issues when using a plan to remote backend state that's used in subsequent apply. If you use a conditional for expression instead of the lookup function that should resolve the issue. 

For example: 
```
# Avoid using the lookup function
{ service      = lookup(var.map, "service", null) }
# Use a conditional for expression instead
{ service      = length([for k, v in var.map : v if k == "service"]) > 0 ? var.map.service : null }
```

**Comment by jcollum** [comment]
We ran into this yesterday. Running a deploy without the timestamp tag and then running another one with the timestamp tag sorted it out.

**Comment by ravishtiwari-labs** [comment]
issue still persists with tf 1.1.0:
```
terraform --version
Terraform v1.1.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.59.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

Again, default_tags are defined here for provider.

**Comment by ravishtiwari** [comment]
I ran into this yesterday, this is the error:

```
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_mwaa_environment.airflow_env to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element
│ "Name" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```

issue still persists with tf 1.1.0:

```
terraform --version
Terraform v1.1.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.59.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

Again, default_tags are defined here for the provider.

**Comment by abjoseph** [comment]
I'm stilling encountering the following error as others have stated:

```
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_instance.win_db_instance to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new     
│ element "Hostname" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```
issue still persists with tf 1.1.6:
```
C:\Workspace\Git\random_project>terraform --version
Terraform v1.1.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.74.3
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```
default_tags are also defined for the provider.

**Comment by dsantanu** [comment]
The very same issue for me too, using `aws_s3_bucket` resource:

> provider "register.terraform.io/hasicorp/aws" produced an invalid new value for .tags_all: new element "Name" has appeared.

My config is something like this:

```
tags = merge(
  var.extra_tags,
  {
    Name = "${local.bucket_id_pfx}-${random_id.s3_bucket.hex}"
  }
)
```
The error goes away if I [re]apply second time, without doing anything else and only happens during S3 bucket operation for me.

```
Terrafrom: v0.13.6
Provider:  v4.0.0
```

**Comment by jcollum** [comment]
@dsantanu it's not going to fix the issue but your TF is very outdated.

**Comment by davepattie** [comment]
We're very close to removing default_tags all together and adding them manually into each resource.  It's often resolved by applying a second time but please can we get an update on this issue? It seems to have started affecting us more frequently in the last 2 weeks

**Comment by dsantanu** [comment]
> @dsantanu it's not going to fix the issue but your TF is very outdated.

its got nothing to do with TF version, but the provider. People are getting very same issue with v0.14.xx, v0.15.xx and even v1.x.xx, not just v0.13.xx

**Comment by dsantanu** [comment]
Is there any update on this issue? Some _inexperienced_ members from the extended team keep reporting that the terraform code/module provided by cloud-engineering team not working, which driving me crazy, spending additional time explaining the reasons to various stake holders. It's really not acceptable hanging us in the middle for such a long period of time.

**Comment by thomasschuiki** [comment]
Hi,

we are also running into this issue. We are using a _random_string_ resource to generate a suffix for the names of resources. What worked for me was to create the dynamic resource first and after that apply the whole config.

1. `terraform apply -var-file=vars/dev.tfvars -target "random_string.suffix"`
2. `terraform apply -var-file=vars/dev.tfvars`

Maybe this helps someone else.

**Comment by majusmisiak** [comment]
Since it hasn't been mentioned yet, thread [Using default_tags {}](https://github.com/hashicorp/terraform-provider-aws/issues/19583) has very detailed explanation why this error occurs and possible solutions. In short, this is issue comes from Terraform SDK and is not something that AWS Provider can resolve on their own.

As to solution - Do not use derived values for tags. You should use only values that are known ahead of time. This is the correct way.

If for any reason you can't do above, you can use one of the following workarounds
1. Re-apply the terraform. It will work on the second run (this was already mentioned above).
2. Run terraform in two stages, first `terraform apply -target=aws_instance.example` then `terraform apply`. First run creates all needed values.
3. Override statically the problematic from calling module. For example, set statically tag ` CreatedAt = "0" ` at the top-level terraform (or terragrunt) file.

**Comment by fitchtech** [comment]
In my honest opinion if the SDK is causing the issue then either that should be fixed or change the implementation pattern in the provider for default tags. It shouldn't be so complicated, the fact that it doesn't work effectively and causes more issues than it helps makes me avoid using it all together. 

Tags are just a key value map and if a value for a given key isn't known until apply it shouldn't matter. If it's unknown then plan an update for that key. Prior to them adding the default tags feature all resources that supported tags already had a property for tags. So adding 'all_tags' seems redundant. Just merge the maps from a default tag variable into the tags properly of each resource that supports it. 

That's what I do when developing a module, use a default tags variable. Which that works fine and never had an issue with setting a tags map that's applied to all resources. So honestly I don't see why it should be so cumbersome to do that in the provider itself. As it is now I find this feature more trouble than it's worth.

**Comment by majusmisiak** [comment]
> @majusmisiak - Can you clarify exactly what you mean for the second workaround you propose? I'm not following how this line would need to be updated: -target=aws_instance.example. Would you do this for each resource?

@ome-eo This works in case, where in single module you have 2 (or more) resources, where resource A has output that is used as a tag by resource B. Then you can run `terraform apply -target=A ; terraform apply -target=B` without getting an error.

You would have to do that for each resource that creates outputs used as tags by other resources.

**Comment by prkottam** [comment]
Ran into this  issue while upgrading Aurora Postgres engine from 10.18 to 10.19 or 10.20; result is same with combination of multiple versions of aws providers and terraform.
`│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_rds_cluster_instance.instances[0] to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .engine_version: was cty.StringVal("10.20"), but now
│ cty.StringVal("10.18").
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.`

**Comment by jpriebe** [comment]
Use of random_string in Name tag causes this problem for us.  We have compelling use cases for using random strings in resource names (to prevent collision of Secrets Manager secrets, for example, if you have to terraform destroy and then terraform apply -- secrets aren't deleted immediately, they get schedule for deletion)

We deploy via pipelines, so the whole "apply twice" strategy really sucks for us.  We need non-TF-experts to be able to deploy after making configuration changes.  It's going to make it very challenging if applying the terraform requires a terraform shaman to read the tea leaves and conclude "oh, just run a plan and apply again, and everything will be fine".  How can you get non-believers to get on the IAC train if it's this wonky?

**Comment by saiaman** [comment]
still no solution to this problem ???? it's a big deal for me

**Comment by nicoodle** [comment]
We've hit this issue as well now, luckily re-running Terraform fixes it but we'd like to avoid a double apply. 

Example of error:
```
Error: Provider produced inconsistent final plan
When expanding the plan for module.okp.aws_eks_node_group.private["BaseM5AD"]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.tags_all: new element "k8s.io/cluster-autoscaler/enabled" has appeared.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Terraform Version: v1.1.9
Provider Version: v4.22.0

**Comment by qtruong77** [comment]
Encounter the same issue as @nicoodle , 2nd apply will be good.
Sample error:
```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.glue_workflow_datamart["booking_datamart_tables_refresh"].module.glue_job_datamart["booking_datamart_itinerary_fact_refresh_glue_job"].aws_glue_trigger.glue_trigger["booking_datamart_customer_stats_refresh_glue_trigger"]
│ to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .predicate[0].conditions[2].job_name: was
│ cty.StringVal("booking_datamart_ssr_fact_refresh_glue_job"), but now cty.StringVal("booking_datamart_product_fact_refresh_glue_job").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```
My environment
```
Terraform v1.2.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.22.0
```

**Comment by Jpk518** [comment]
I've been hitting this issue similarly, but with a specific subproblem I have many already existing resources with a dynamic tag `CreatedAt=timestamp()` already defined and when I try implementing a default_tags block, all state files containing the aforementioned resources get bricked. 

A solution here is to define an additional parameter in the provider block `ignore_tags { keys = ["CreatedAt"] }` and this will bypass the inconsistent value on the timestamp() allowing a successful apply. What's weird is that this solution only works when the underlying resource has the single `CreatedAt` tag, and if the resource contains additional tags such as `Name=test` the ignore_tags will stop working and I'm back to step one with the "inconsistent final plan" where it will attempt to calculate the timestamp(). Has anyone else been down the rabbit hole for this specific subproblem of this bug and found a better workaround?

**Comment by FernandoMiguel** [comment]
> I've been hitting this issue similarly, but with a specific subproblem where I have many existing resources with a dynamic tag `CreatedAt=timestamp()` already defined and after implementing a default_tags block, the state files containing the aforementioned resources become bricked with the "inconsistent final plan" error. 
> 
> A solution here is to define an additional parameter in the provider block `ignore_tags { keys = ["CreatedAt"] }` and this will bypass the inconsistent value on the timestamp() allowing a successful apply. What's weird is that this solution only works when the underlying resource has the single `CreatedAt` tag, and if the resource contains additional tags such as `Name=test` the ignore_tags will stop working and I'm back to step one with the "inconsistent final plan" where it will attempt to calculate the timestamp(). Has anyone else been down the rabbit hole for this subproblem of the bug and found a better workaround?
> 

That's a super great trick. I didn't know about.
Shame it does not work for name tag which is the one that commonly affects SGs!

**Comment by Jpk518** [comment]
> That's a super great trick. I didn't know about. Shame it does not work for name tag which is the one that commonly affects SGs!

Sorry I should have been more specific on exactly how the workaround seems to work. From my testing, if a resource has a dynamic tag (e.g. `CreatedAt=timestamp()`) and we want to implement the default_tags in the provider, we can get around this bug by somehow skipping the resource tags all together (e.g. adding every tag to the providers `ignore_tags` block like we did above if a resource only has 1 tag) and terraform will not read/parse the tags block in the resource at all including the dynamic tag and will apply correctly. 

Where this solution falls flat is that if the resource has multiple tags, where all the other tags besides `CreatedAt` are static and fine, and we want to ignore only the "broken" `CreatedAt` tag. So for example if the other tags on a resource are static (e.g. I have a resource with: `tags = { CreatedAt=timestamp(), TestTag=Tag`) and I ignore the `CreatedAt` tag with `ignore_tags { keys = ["CreatedAt"] }`, the plan/apply will still notice the `TestTag` in the resources tag block, and even though the other tag is static and valid, because terraform tries to parse the entire tag block if there is any change to any tag it will pick up the broken `CreatedAt` tag in that parse that was supposed to be ignored and will fail completely again.

Because of above and how terraform parses changes in tags my solution isn't very viable as it will only work if you ignore every tag so the tags block doesn't get scanned at all by terraform. What we really want is the `ignore_tags` block to not scan the specific tags in it as opposed to just not updating them, and I don't think there is any way to do that currently unfortunately :(

**Comment by viatcheslavmogilevsky** [comment]
"re-applying" workaround for those who using terratest:

```go
terraformOptions := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
                 // these options are for example
		TerraformDir: "../test_root_module",
		Upgrade:      true,
		Vars: map[string]interface{}{
			"id":             exampleId,
                }
		Parallelism: x
	})
	
// this line did the trick:
terraformOptions.RetryableTerraformErrors[".*\\.tags_all: new element \".+\" has appeared\\..*"] = "Provider produced inconsistent final plan"


defer terraform.Destroy(t, terraformOptions)
terraform.InitAndApply(t, terraformOptions)
```

**Comment by pixelicous** [comment]
We just hit the same problem, this bug is open for over a year, any eta from hashicorp when it will be solved?

**Comment by popsicleslayer** [comment]
Run into the same problem while creating a cognito user.
`Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_cognito_user.example to include
│ new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .attributes: was null, but now
│ cty.MapVal(map[string]cty.Value{"email":cty.StringVal("user@example.com"),
│ "email_verified":cty.StringVal("true")}).
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
`

**Comment by tata2000** [comment]
Same here, hitting this problem since started to use default tags. 
It also impacts the testing experiment that now fails 100% of the times. 
Manually succeeded to overcome this problem with execution of additional apply.

**Comment by jcano-chwy** [comment]
Just ran into this error with API gateway suddenly. We are using Jenkins for deployment jobs and rerunning the Jenkins job made this go away.
```

12:18:12  │ Error: Provider produced inconsistent final plan
12:18:12  │ 
12:18:12  │ When expanding the plan for aws_api_gateway_deployment.rest_api to include
12:18:12  │ new values learned so far during apply, provider
12:18:12  │ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
12:18:12  │ .triggers["trigger_hash"]: was
12:18:12  │ cty.StringVal("0ef5fcdbd32e2833e9b2ca380e8cad985c7cc3fa"), but now
12:18:12  │ cty.StringVal("76330dbc8c967581e991f1e69000fa88674d31c8").
12:18:12  │ 
12:18:12  │ This is a bug in the provider, which should be reported in the provider's
12:18:12  │ own issue tracker.
12:18:12  ╵
```

**Comment by jcano-chwy** [comment]
Just ran into this error with API gateway suddenly. We are using Jenkins for deployment jobs and rerunning the Jenkins job made this go away.


12:18:12  │ Error: Provider produced inconsistent final plan
12:18:12  │ 
12:18:12  │ When expanding the plan for aws_api_gateway_deployment.rest_api to include
12:18:12  │ new values learned so far during apply, provider
12:18:12  │ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
12:18:12  │ .triggers["trigger_hash"]: was
12:18:12  │ cty.StringVal("..."), but now
12:18:12  │ cty.StringVal("...").
12:18:12  │ 
12:18:12  │ This is a bug in the provider, which should be reported in the provider's
12:18:12  │ own issue tracker.
12:18:12  ╵

**Comment by mmierzwa** [comment]
I have the same issue with AppSync change:
```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.tutoring_api_appsync_tutorqa_recent_progress_ext_resolver.aws_appsync_resolver.resolver
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.data_source: was
cty.StringVal("tut_tso_get_tutorqa_recent_progress_ext_proxy_development"),
but now
cty.StringVal("tutoring_get_tutorqa_recent_progress_ext_proxy_development").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

```
hashicorp/aws v3.75.2
```

**Comment by ash-murphy-colibri** [comment]
│ When expanding the plan for module.vpc.aws_iam_role.vpc_flow_logs to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element
│ "Name" has appeared.

**Comment by manas86** [comment]
Is there any proper solution provided for this issue? I'm getting same error for all most all resources, this is just an example
`│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ aws_servicecatalog_portfolio.sagemaker_portfolio to include new values
│ learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
│ produced an invalid new value for .tags_all: new element "account_name" has
│ appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.`
I have tried apply and re-apply and apply again with solution suggested `-target=aws_servicecatalog_portfolio.sagemaker_portfolio` it throws me 
```
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes
│ requested in the configuration may have been ignored and the output values
│ may not be fully updated. Run the following command to verify that no other
│ changes are pending:
│     terraform plan
│ 	
│ Note that the -target option is not suitable for routine use, and is
│ provided only for exceptional situations such as recovering from errors or
│ mistakes, or when Terraform specifically suggests to use it as part of an
│ error message.
```
This issue happens `tags          = {} -> (known after apply) ` 

having a resource tags set with a var is not not being picked by tags, though presumably it's in the similar situation where the tag value is known_after_apply) 

Any solution would be really helpful.

**Comment by jgeurts** [comment]
It's a terraform bug that hashicorp refuses to acknowledge/fix. In my case, I was able to have part of my resource name include a date string, rather than putting the date as a tag. Not ideal, but it allowed me to move on.

**Comment by soumentrivedi** [comment]
I have been able to get around this issue by defining the ignore_tags { keys = ["..."] } block in the provider and i can see the the resource specific tags and the default_tags are working. i followed the comment from @Jpk518 in this thread. in my case the specific issue was with the vpc_subnet tagging which were all generated at runtime.

**Comment by kristofdho** [comment]
Similar issue, again to do with `timestamp()` has popped up here: https://github.com/hashicorp/terraform-provider-aws/issues/28070

**Comment by ignamlrz** [comment]
I ran into this with the aws_ecs_service resource. Terraform v1.3.1 and AWS provider v4.40.0 and v4.47.0

```
resource "aws_ecs_service" "selected" {
  # Configure service
  task_definition = aws_ecs_task_definition.service.arn
  launch_type     = "FARGATE"
  cluster         = data.aws_ecs_cluster.selected.id
  name            = "${var.name}-f-service"
  desired_count   = 1
  # Configure network
  network_configuration {
    assign_public_ip = false
    subnets          = var.service_subnets
    security_groups  = var.service_security_groups
  }
  health_check_grace_period_seconds = 0
  load_balancer {
    target_group_arn = aws_lb_target_group.service.arn
    container_name   = "${var.name}-container"
    container_port   = length(var.port_mappings) == 0 ? 8080 : var.port_mappings[0].containerPort
  }
  force_new_deployment = true
  triggers = {
    redeployment = timestamp()
  }
}
```

When I do:
`terraform apply` I get the following:

```
When expanding the plan for module.service.aws_ecs_service.selected to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value  
│ for .triggers["redeployment"]: was cty.StringVal("2022-12-19T15:47:17Z"), but now cty.StringVal("2022-12-20T07:51:30Z").
```

**Comment by lee-vincent** [comment]
For this error,

`Error: Provider produced inconsistent final plan
When expanding the plan for aws_ami_copy.server_encrypted to include
new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.tags_all: new element "Name" has appeared.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.`

Just define Name = "" in default tags and also have Name set to the real value in your resources

`provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
  default_tags {
    tags = {
      automation = "terraform-managed",
      Name       = ""
    }
  }
}`

`resource "aws_subnet" "db" {
  vpc_id            = aws_vpc.tf_vpc.id
  cidr_block        = "10.16.3.0/24"
  availability_zone = format("%s%s", var.aws_region, var.aws_zone)
  tags = {
    Name = format("%s%s%s%s", var.aws_prefix, var.aws_region, "-db-subnet", "-${random_id.demo_id.id}")
  }
}`

**Comment by morremeyer** [comment]
@kevinashaw Does this issue **prevent** applying your module/workspace? In our case, it's only annoying and a re-apply resolves it.

I was assuming this is how it behaves for everyone so I wasn't wondering about why it wasn't prioritized higher.

**Comment by kevinashaw** [comment]
Well, I had to rebuild the network due to an error, but was unable to run it and I didnt want to destroy it.  The only other option was to remove EVERY TAG from our network stack.  I can now re-apply the stack but have lost all names and all tags.  Attempting to re-introduce tags causes the error to come back.  We have a dozen subnets and can't tell one from the other (except by tracking the hex identifier).  Very frustrating.  It would help a lot of this could be fixed!

**Comment by smellyspice** [comment]
I had the same error but for an SSM parameter: 
```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_ssm_parameter.dns_zone_ids to include new
│ values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .value: inconsistent values for sensitive attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```
I re-ran the `apply` and got no further error messages. However, the modification to the SSM parameter would not update to the new value. Further `plan`s showed TF wanting to do an update, `apply`ing reported success, but in fact, the Store did not update. I tried updating to the latest provider version, same result. 

However, during my troubleshooting the instance I was running on ran out of disk space. I wonder if this error is somehow caused when the right combination of available space is exhausted, at just the right time, during a TF run. I didn't see any error message of disk space in the first few trace runs I did while troubleshooting, but wasn't specifically looking for those kinds of error messages either. As a side note, the TF code is run via Terragrunt - so there is lots of cache directories that get created -- further eating up disk space.

**Comment by GaroneTux** [comment]
Hi folks!
More one victim. . . 

Terraform v1.3.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.56.0
+ provider registry.terraform.io/hashicorp/random v3.4.3

Abstract: 
In my case I want to create ec2 instances with and for generate name for those instaces, I've using count, randon_pet and one variable type list called "local_env" with default values ["development", "staging", "production"] . All itens put on tags block with interpolation and variables.
I can use tags for create name for instances
 A part of code expalined:

`
resource "aws_instance" "server02" {
  ami = data.aws_ami.soubuntu.id
  instance_type = "t2.micro"
  count = 1
  key_name                    = aws_key_pair.key00.id
  subnet_id                   = data.terraform_remote_state.vpc.outputs.subnet_id2
  vpc_security_group_ids      = [data.terraform_remote_state.vpc.outputs.security_group_id]
  associate_public_ip_address = true
   tags = {
    Name = "vm-${count.index}${random_pet.vms_name.id}-${var.local_env[0]}"
  } 
}
`
I ran the validate and plan commands and everything ok, but when will I run apply. . . The error appear:

` 
Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_instance.server01[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name"
│ has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
`

Hashicorp, since May 2021 making us happier. . .

**Comment by Jpk518** [comment]
Think this issue might be getting fixed in next major release of the provider https://github.com/hashicorp/terraform-provider-aws/issues/29842

**Comment by glg-satish-tripathi** [comment]
I faced the same issue:
```terraform
resource "aws_subnet" "spacelift_public_subnet" {
  vpc_id                  = var.vpc_id
  count                   = length(var.spacelift_public_subnets_cidr)
  cidr_block              = element(var.spacelift_public_subnets_cidr, count.index)
  availability_zone_id    = element(var.availability_zone_ids, count.index)
  map_public_ip_on_launch = true
  tags = {
    Name = "${var.name}-${element(var.availability_zone_ids, count.index)}-public-subnet"
  }
}
resource "aws_security_group" "spacelift_sg" {
  description = "Security group to allow inbound/outbound from the VPC"
  vpc_id      = var.vpc_id

  ingress {
    from_port = 0
    to_port   = 0
    protocol  = "-1"
    # Primary vpc cidr in infrastructure-management account.
    cidr_blocks = [var.vpc_cidr]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "${var.name}"
  }
} 
```
In some runs this fails. 

Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.spacelift_networking.aws_subnet.spacelift_public_subnet[1] to include new values learned so far during apply, provider “[registry.terraform.io/hashicorp/aws](http://registry.terraform.io/hashicorp/aws)” produced an
│ invalid new value for .tags_all: new element “Name” has appeared.
│
│ This is a bug in the provider, which should be reported in the provider’s own issue tracker.

**Comment by DoyleDev** [comment]
another victim of this bug, please fix Hashicorp 😢

**Comment by ofey404** [comment]
Hi, there.

A new victim appears.

Version:

```
Terraform v1.4.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.66.1
```

I use eks blueprints, but basically the problem lies on the managed node group.

```hcl
module "eks_blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.25.0"
  tags         = local.tags
}
```

Error output:

```
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.eks_testing.module.eks_blueprints.module.aws_eks_managed_node_groups["basic"].aws_eks_node_group.managed_ng to include new values learned so far during apply, provider        
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "managed-by" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

**Comment by rajmartha26** [comment]
one more victim. 

@johnsonaj  when you say it is merged that means this problem is fixed? what version of TF we need to use?

**Comment by qa97** [comment]
another victim
Hashicorp, please help

│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.kafka.module.broker_security_group.aws_security_group.default[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .tags_all: new element "Stage" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.eks_node_group.aws_launch_template.default[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element
│ "Attributes" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.eks_node_group.aws_launch_template.default[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element
│ "Name" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.eks_node_group.aws_launch_template.default[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element
│ "Namespace" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.eks_node_group.aws_launch_template.default[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element
│ "Stage" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.eks_node_group.aws_launch_template.default[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element
│ "k8s.io/cluster-autoscaler/enabled" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.eks_node_group.aws_launch_template.default[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element
│ "k8s.io/cluster-autoscaler/witty-temp-test-cluster-cluster" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.eks_node_group.aws_launch_template.default[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element
│ "kubernetes.io/cluster/witty-temp-test-cluster-cluster" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by johnsonaj** [comment]
@rajmartha26 we have done work to allow resource `tags` to be `computed` values. This update will be released in `v5.0.0` of the provider. 

It is still not possible to have `computed` values in the provider level `default_tags` block. This is due to limitations on how the provider is configured and how these `default_tags` are applied to resources downstream.

The following configuration will be possible in `v5.0.0`
```terraform
provider "aws" {
  region = "us-west-2"
}

resource "aws_s3_bucket" "example" {
  bucket = "example-bucket"
  tags = {
    created_at = timestamp()
  }
}
```

However, the follow will still not compute correctly because `default_tags` must be known values

```terraform
provider "aws" {
  region = "us-west-2"
  default_tags {
    tags = {
        created_at = timestamp()
    }
  }
}

resource "aws_s3_bucket" "example" {
  bucket = "example-bucket"
}
```

**Comment by johnsonaj** [comment]
> @johnsonaj something like below will be possible in v5.0.0 ?
> 
> ```
> provider "aws" {
>   region = "us-west-2"
>   default_tags {
>     tags = {
>         additional_tag = "value"
>        additional_tag = "value-2"
>         
>     }
>   }
> }
> 
> resource "aws_s3_bucket" "example" {
>   bucket = "example-bucket"
>   tags     = {
>     created_at = timestamp()
>   }
> }
> ```

@rajmartha26 yes, that will be possible when `v5` is released. The `timestamp()` function will change values on every run since it includes time, so this may not be the best example, however `computed` values will be accepted

**Comment by rajmartha26** [comment]
@johnsonaj  yes timestampfunction will chage and we are add that in ignore_changes, 

Any time line when the v5 will release?

**Comment by DarrenBishop** [comment]
Hi @johnsonaj I am not sure what constitutes a 'computed value'; does it include vars passed in via `TF_VAR_` or `-var-file blah.tfvars`?

I am standing up EKS and deploying a bunch of Helm charts (`helm_release`) - in a sense for multi-tenancy, hence the vars going into default-tags - and this issue causes a mess; the plan from a clean slate has 94+ resources, but the true number is greater.

**Comment by nazarewk** [comment]
I'm also observing the issue today
