### ISSUE TITLE
AWS provider 3.69.0 to latest version- MalformedPolicyDocument: The policy failed legacy parsing

### ISSUE THREAD

**Issue by dragosrosculete** [hashicorp/terraform-provider-aws#26108]
Hello,

Yesterday I have upgraded the AWS provider to latest version and my IAM policy fails to work

```
resource "aws_iam_policy" "cross-account-ai-developer" {
  name   = "cross-account-ai-developer"
  description = "cross-account-ai-developer"
  path   = "/"
  policy = <<-EOF
{
    "Version": "2012-10-17",
    "Statement": {
        "Effect": "Allow",
        "Action": "sts:AssumeRole",
        "Resource": [
            "arn:aws:iam::xxxx:role/cross-account-ai-developer",
            "arn:aws:iam::xxxx:role/cross-account-ai-developer",
            "arn:aws:iam::xxxx:role/cross-account-ai-developer",
            "arn:aws:iam::xxxx:role/cross-account-ai-developer"
        ]
  }
}
EOF
}
```

Getting the error 
```
aws_iam_policy.cross-account-ai-developer: Creating...
╷
│ Error: error creating IAM policy cross-account-ai-developer: MalformedPolicyDocument: The policy failed legacy parsing
│ 	status code: 400, request id: fda3e9e6-eb63-4d2c-a2e2-1b98e13fe95b
│ 
│   with aws_iam_policy.cross-account-ai-developer,
│   on policy.tf line 762, in resource "aws_iam_policy" "cross-account-ai-developer":
│  762: resource "aws_iam_policy" "cross-account-ai-developer" {
│ 
╵
Releasing state lock. This may take a few moments...
```

After an investigation I have found the last version this still works is 3.68.0 . It will start to fail from version 3.69.0.
Code changes between versions are here
https://github.com/hashicorp/terraform-provider-aws/compare/v3.68.0...v3.69.0

Can you please tell me why this doesn't work/ not supported anymore ?
I have thousands of IAM policies defined this way because it makes it easier to just copy a policy (keep format) and place it in terraform and vice versa.

**Comment by dragosrosculete** [comment]
Manage to make it work by formating it like this
```
resource "aws_iam_policy" "cross-account-ai-developer" {
  name   = "cross-account-ai-developer"
  description = "cross-account-ai-developer"
  path   = "/"
  policy = jsonencode(
{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": "sts:AssumeRole",
        "Resource": [
            "arn:aws:iam::xxxx:role/cross-account-ai-developer",
            "arn:aws:iam::xxxx:role/cross-account-ai-developer",
            "arn:aws:iam::xxxx:role/cross-account-ai-developer",
            "arn:aws:iam::xxxx:role/cross-account-ai-developer"
        ]
      }
    ]
  }
)
}
```

**Comment by justinretzolk** [comment]
Hey @dragosrosculete 👋 Thank you for taking the time to raise this, and for coming back to let us know you were able to get past it. Given that you were able to resolve this, my inclination is to close this issue out, but before I do, do you feel the issue is sufficiently resolved at this point?

**Comment by dragosrosculete** [comment]
Seems the problem is back, I dont know why :/
Trying to apply this policy and fails

```
resource "aws_iam_policy" "cross-account-developer" {
  name = "cross-account-developer"
  path = "/"
  policy = jsonencode(
    {
      "Version" : "2012-10-17",
      "Statement" : {
        "Effect" : "Allow",
        "Action" : "sts:AssumeRole",
        "Resource" : [
          "arn:aws:iam::xxx:role/cross-account-developer"
        ]
      }
    }
  )
}
