### ISSUE TITLE
[Bug]: error creating ElastiCache Replication Group ( redis7 effect )

### ISSUE THREAD

**Issue by YunWoo0608** [hashicorp/terraform-provider-aws#27709]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.1.0

### Affected Resource(s)

aws_elasticache_replication_group

### Expected Behavior

create redis family 5 ( parameter groups / cluster )

### Actual Behavior

│ Error: error creating ElastiCache Replication Group (testtest-gameDB-redis): InvalidParameterCombination: Expected a parameter group of family redis7 but found one of family redis5.0
│ 	status code: 400, request id: 209c2da9-2ebe-4972-91e3-0363a5e99589

### Terraform Configuration Files

[tf-mod-aws-redis.tar.gz](https://github.com/hashicorp/terraform-provider-aws/files/9966994/tf-mod-aws-redis.tar.gz)

### Steps to Reproduce

terraform init 
terraform plan
terraform apply

### Panic Output

│ Error: error creating ElastiCache Replication Group (testtest-gameDB-redis): InvalidParameterCombination: Expected a parameter group of family redis7 but found one of family redis5.0
│ 	status code: 400, request id: 209c2da9-2ebe-4972-91e3-0363a5e99589
│
│   with module.redis.aws_elasticache_replication_group.this,
│   on ../main.tf line 31, in resource "aws_elasticache_replication_group" "this":
│   31: resource "aws_elasticache_replication_group" "this" {

**Comment by justinretzolk** [comment]
Hey @YunWoo0608 👋 Thank you for taking the time to raise this! I suspect this issue here is your definition for the `engine_version` of the `aws_elasticache_replication_group` resource. You currently have:

```terraform
engine_version             = lookup(var.redis_config, "var.engine_version", null)
```

This is attempting to lookup a key in `var.redis_config` that is the string `var.engine_version`. Since it's not finding that, it's setting `engine_version` to `null`. I suspect that AWS then uses the latest, which would be a mismatch given that `aws_elasticache_parameter_group.pg.family` is being set to `redis5.0`. Updating the lookup to be `engine_version` should resolve the issue.

**Comment by gdavison** [comment]
Hi @YunWoo0608, @justinretzolk is correct that passing a `null` value to `engine_version` will use the default version, which is currently `redis7`.

I'm going to close this issue. Please open a new issue if this does not resolve the problem.
