### ISSUE TITLE
[Bug]: Cloudwatch Logs V2

### ISSUE THREAD

**Issue by scottharris** [hashicorp/terraform-provider-aws#40885]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.83.0

### Affected Resource(s)

aws_cloudwatch_log_delivery

### Expected Behavior

Should create a log delivery connection between the source and destination,  the destination is setup to log to a S3 bucket with output_format set to parquet. 

### Actual Behavior

Fails with error

### Relevant Error/Panic Output Snippet

```shell
Error: Provider produced inconsistent result after apply
 
 When applying changes to aws_cloudwatch_log_delivery.example, provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value: .field_delimiter: was null, but now cty.StringVal("\t").
 
 This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Terraform Configuration Files

```
resource "aws_cloudwatch_log_delivery_source" "example" {
  name         = "name"
  log_type     = "ACCESS_LOGS"
  resource_arn = "arn:aws:cloudfront::123456789012:distribution/123456789012"
}

resource "aws_cloudwatch_log_delivery" "example" {
  delivery_source_name     = aws_cloudwatch_log_delivery_source.example.name
  delivery_destination_arn = "arn:aws:logs:us-east-1:123456789012:delivery-destination:mydestination"
}

resource "aws_cloudwatch_log_delivery_destination" "s3" {
  name          = "mydestination"
  output_format = "parquet"

  delivery_destination_configuration {
    destination_resource_arn = "arn:aws:s3:::mydestination-bucket-us-east-1"
  }
}

resource "aws_cloudwatch_log_delivery_destination_policy" "s3" {
  delivery_destination_name = aws_cloudwatch_log_delivery_destination.s3.name
  delivery_destination_policy = data.aws_iam_policy_document.delivery_destination_policy.json
}
```

### Steps to Reproduce

terraform init
terraform apply

### Important Factoids

I can create the delivery using the awscc without issue as a workaround for now

```
resource "awscc_logs_delivery" "example" {
  delivery_source_name     = aws_cloudwatch_log_delivery_source.example.name
  delivery_destination_arn = "arn:aws:logs:us-east-1:123456789012:delivery-destination:mydestination"

  tags = [ 
    {
      key   = "Name"
      value = "blah"
    }
  ]
}
```

### Would you like to implement a fix?

No

**Comment by scottharris** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/40731

**Comment by ekramer-starz** [comment]
Wanted to add a bit more context that I found out here as I'm running into the same issue and I'm not sure if this is a bug with the provider, or the upstream API itself. 

In addition to the field delimiter value throwing the inconsistency error, I also see the following errors when I create the resource:

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.test_cf.aws_cloudwatch_log_delivery.cloudfront_log_delivery, provider
│ "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value:
│ .s3_delivery_configuration[0].enable_hive_compatible_path: was null, but now cty.False.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.test_cf.aws_cloudwatch_log_delivery.cloudfront_log_delivery, provider
│ "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value:
│ .s3_delivery_configuration[0].suffix_path: was
│ cty.StringVal("/123456678910/{DistributionId}/{yyyy}/{MM}/{dd}/{HH}"), but now
│ cty.StringVal("AWSLogs/{account-id}/CloudFront/123456678910/{DistributionId}/{yyyy}/{MM}/{dd}/{HH}").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

Seems like the first one could maybe be addressed in the provider as the default value when passing null to the API?

However, the delimiter, and suffix path are being passed correctly to the `CreateDelivery` API. The AWS API, however, is changing these resource properties after it's been called. Therefore, a subsequent call to `GetDelivery` is causing the inconsistency to show up. I've reached out to AWS support to see if this is maybe a bug in the API as there is no documentation saying that null delimiters will be converted to `\t` and the suffix path will be changed.

**Comment by gp42** [comment]
I opened a support case with AWS, let's see what they say about the suffix change after the initial API call.

**Comment by kbachuHighSpot** [comment]
Not sure where to ask this question. Posting it here for help.

I am getting below error when I try cloudfront logs to cloudwatch with new logs delivery feature.

> operation error CloudWatch Logs: PutDeliveryDestinationPolicy, https
> 
> │ response error StatusCode: 400, RequestID:
> 
> │ 7e4cd55c-21cf-4e4a-99a0-6e566b38e64d, ValidationException: Invalid Delivery
> 
> │ Destination resource Policy is provided.
> 
> 

`
resource "aws_cloudwatch_log_delivery_source" "cloudfront_logs" {
  name         = "cloudfront-logs"
  log_type     = "ACCESS_LOGS"
  resource_arn = aws_cloudfront_distribution.customer_content_cdn.arn
}

resource "aws_cloudwatch_log_delivery" "cloudfront_logs" {
  delivery_source_name     = aws_cloudwatch_log_delivery_source.cloudfront_logs.name
  delivery_destination_arn = aws_cloudwatch_log_delivery_destination.cloudwatch_log_group.arn
}

resource "aws_cloudwatch_log_delivery_destination" "cloudwatch_log_group" {
  name          = "cloudwatch-logs"
  output_format = "json"

  delivery_destination_configuration {
    destination_resource_arn = aws_cloudwatch_log_group.cloudfront_logs.arn
  }
}

resource "aws_cloudwatch_log_delivery_destination_policy" "cloudfront_logs" {
  delivery_destination_name   = aws_cloudwatch_log_delivery_destination.cloudwatch_log_group.name
  delivery_destination_policy = data.aws_iam_policy_document.cloudfront_logs_policy.json
}

resource "aws_cloudwatch_log_group" "cloudfront_logs" {
  name              = "/aws/cloudfront/logs-content-cdn"
  retention_in_days = 90
}

data "aws_iam_policy_document" "cloudfront_logs_policy" {
  statement {
    actions = [
      "logs:CreateLogGroup",
      "logs:CreateLogStream",
      "logs:DescribeLogGroups",
      "logs:DescribeLogStreams",
      "logs:PutLogEvents",
    ]

    resources = ["*"]
  }
}
`

**Comment by derekleegh** [comment]
> Not sure where to ask this question. Posting it here for help.
> 
> I am getting below error when I try cloudfront logs to cloudwatch with new logs delivery feature.
> 
> CloudFront distribution is existing one in the account and it doesn't have associations with logs delivery.
> 
> > Error: creating CloudWatch Logs Delivery Source (cloudfront-logs)
> > │
> > │   with aws_cloudwatch_log_delivery_source.cloudfront_logs,
> > │   on cdn.tf line 229, in resource "aws_cloudwatch_log_delivery_source" "cloudfront_logs":
> > │  229: resource "aws_cloudwatch_log_delivery_source" "cloudfront_logs" {
> > │
> > │ operation error CloudWatch Logs: PutDeliverySource, https response error
> > │ StatusCode: 400, RequestID: f7adfff0-9799-45b7-a73f-61c0c28c7bc6,
> > │ ConflictException: This ResourceId has already been used in another
> > │ Delivery Source in this account.
> 
> > operation error CloudWatch Logs: PutDeliveryDestinationPolicy, https
> > │ response error StatusCode: 400, RequestID:
> > │ 7e4cd55c-21cf-4e4a-99a0-6e566b38e64d, ValidationException: Invalid Delivery
> > │ Destination resource Policy is provided.
> 
> ` resource "aws_cloudwatch_log_delivery_source" "cloudfront_logs" { name = "cloudfront-logs" log_type = "ACCESS_LOGS" resource_arn = aws_cloudfront_distribution.customer_content_cdn.arn }
> 
> resource "aws_cloudwatch_log_delivery" "cloudfront_logs" { delivery_source_name = aws_cloudwatch_log_delivery_source.cloudfront_logs.name delivery_destination_arn = aws_cloudwatch_log_delivery_destination.cloudwatch_log_group.arn }
> 
> resource "aws_cloudwatch_log_delivery_destination" "cloudwatch_log_group" { name = "cloudwatch-logs" output_format = "json"
> 
> delivery_destination_configuration { destination_resource_arn = aws_cloudwatch_log_group.cloudfront_logs.arn } }
> 
> resource "aws_cloudwatch_log_delivery_destination_policy" "cloudfront_logs" { delivery_destination_name = aws_cloudwatch_log_delivery_destination.cloudwatch_log_group.name delivery_destination_policy = data.aws_iam_policy_document.cloudfront_logs_policy.json }
> 
> resource "aws_cloudwatch_log_group" "cloudfront_logs" { name = "/aws/cloudfront/logs-content-cdn" retention_in_days = 90 }
> 
> data "aws_iam_policy_document" "cloudfront_logs_policy" { statement { actions = [ "logs:CreateLogGroup", "logs:CreateLogStream", "logs:DescribeLogGroups", "logs:DescribeLogStreams", "logs:PutLogEvents", ]
> 
> ```
> resources = ["*"]
> ```
> 
> } } `

This is usually caused by manual enabling of the logs delivery to S3. 

To solve this issue, first run the following command to list existing delivery-source. 
`aws logs describe-delivery-sources --region us-east-1`

You should be able to see 1 with name like `CreatedByCloudFront-xxx` on it. Then run `aws logs delete-delivery-source --name CreatedByCloudFront-xxx` to delete it.

**Comment by derekleegh** [comment]
Do we have the fix implemented already? if yes, is there an example? I've using provider v5.85.0. 

The delimiter error seems to be gone but when i set suffix_path to `"{yyyy}/{MM}/{dd}/{HH}/"` it still shows as inconsistent.

**Comment by ekramer-starz** [comment]
> Do we have the fix implemented already? if yes, is there an example? I've using provider v5.85.0.
> 
> The delimiter error seems to be gone but when i set suffix_path to `"{yyyy}/{MM}/{dd}/{HH}/"` it still shows as inconsistent.

Based on the description of #41122, it sounds like most/all of these issues except the suffix path issue have been resolved. However, the suffix path changes are mostly a result of some weird upstream API behavior where this value is dependent on the arn specified for the delivery destination. As a workaround for now, I'm doing the following on the delivery destination resource:

```
resource "aws_cloudwatch_log_delivery_destination" "cloudfront_log_dest" {
  name = "example-cloudfront-destination-logs"

  output_format = "parquet" //whatever output format you're using

  delivery_destination_configuration {
    destination_resource_arn = "arn:aws:s3:::bucket-name/CloudFrontLogs"
  }
}
```

When this is referenced with the `aws_cloudwatch_log_delivery` resource, it results in a successful creation of the delivery that doesn't cause inconsistency errors, but there is an additional prefix in the log destination bucket.

**Comment by scottharris** [comment]
Have tested with the new changes and working for me.  I'm setting a path on the destination so not having any issues with that

**Comment by kbachuHighSpot** [comment]
Thank you @ewbankkit  for the response.

I deleted all existing sources but still running into issues. Could you please help with this issue? This has been a blocker for us.

Error: creating CloudWatch Logs Delivery Source (content-cdn-cloudfront-logs)
│ 
│   with module.scale_unit.aws_cloudwatch_log_delivery_source.cloudfront_logs,
│   on .terraform/modules/scale_unit/cdn.tf line 176, in resource "aws_cloudwatch_log_delivery_source" "cloudfront_logs":
│  176: resource "aws_cloudwatch_log_delivery_source" "cloudfront_logs" {
│ 
│ operation error CloudWatch Logs: PutDeliverySource, exceeded maximum number
│ of attempts, 25, https response error StatusCode: 500, RequestID:
│ bb0e4ad9-6e76-4257-a0ef-c7a02a69be5d, ServiceUnavailableException: Server
│ failed to fulfill the request. Please try again.
╵
╷
│ Error: creating CloudWatch Logs Delivery Destination Policy (content-cdn-cloudwatch-logs)
│ 
│   with module.scale_unit.aws_cloudwatch_log_delivery_destination_policy.cloudfront_logs,
│   on .terraform/modules/scale_unit/cdn.tf line 201, in resource "aws_cloudwatch_log_delivery_destination_policy" "cloudfront_logs":
│  201: resource "aws_cloudwatch_log_delivery_destination_policy" "cloudfront_logs" {
│ 
│ operation error CloudWatch Logs: PutDeliveryDestinationPolicy, https
│ response error StatusCode: 400, RequestID:
│ ee41efa4-8fc3-4c1d-b636-ae9a35d4c21a, ValidationException: Invalid Delivery
│ Destination resource Policy is provided.


`
resource "aws_cloudwatch_log_delivery_source" "cloudfront_logs" {
  name         = "content-cdn-cloudfront-logs"
  log_type     = "ACCESS_LOGS"
  resource_arn = aws_cloudfront_distribution.customer_content_cdn.arn
}

resource "aws_cloudwatch_log_delivery" "cloudfront_logs" {
  delivery_source_name     = aws_cloudwatch_log_delivery_source.cloudfront_logs.name
  delivery_destination_arn = aws_cloudwatch_log_delivery_destination.cloudwatch_log_group.arn
}

resource "aws_cloudwatch_log_delivery_destination" "cloudwatch_log_group" {
  name          = "content-cdn-cloudwatch-logs"
  output_format = "json"

  delivery_destination_configuration {
    destination_resource_arn = aws_cloudwatch_log_group.cloudfront_logs.arn
  }
}

resource "aws_cloudwatch_log_group" "cloudfront_logs" {
  name              = "/aws/cloudfront/logs-content-cdn/xyz0-abc0"
  retention_in_days = 90
}

resource "aws_cloudwatch_log_delivery_destination_policy" "cloudfront_logs" {
  delivery_destination_name = aws_cloudwatch_log_delivery_destination.cloudwatch_log_group.name
  delivery_destination_policy = data.aws_iam_policy_document.log_delivery_policy.json
}

data "aws_iam_policy_document" "log_delivery_policy" {
  statement {
    sid = "AllowCloudWatchLogsDelivery"
    effect = "Allow"

    principals {
      type = "Service"
      identifiers = [
        "delivery.logs.amazonaws.com",
      ]
    }

    actions = [
      "logs:CreateLogStream",
      "logs:PutLogEvents",
    ]

    resources = [
      "arn:aws:logs:*:*:*",
    ]
  }
}
`

**Comment by tkriviradev** [comment]
I am testing with the following terraform setup, however, I am getting strange errors.

│ operation error CloudWatch Logs: PutDeliverySource, https response error StatusCode: 400, RequestID:
│ eed22bcc-859a-4cdf-bcae, ConflictException: This ResourceId has already been used in another Delivery Source in this
│ account.

I am using a dual-provider setup so that I can interact with two Regions at the same time.

This one is using us-east-1

```hcl
resource "aws_cloudwatch_log_group" "access_logs" {
  count             = var.logging.logging_retention > 0 ? 1 : 0
  provider          = aws.region
  name              = "aws-cf-access-logs-${var.resources_prefix}"
  retention_in_days = var.logging.logging_retention
  kms_key_id        = aws_kms_key.logging[0].arn
}

resource "aws_cloudwatch_log_delivery_source" "cloudfront_logs" {
  count        = var.logging.logging_retention > 0 ? 1 : 0
  # provider     = aws.region
  name         = "cloudwatch-access-logs-${var.resources_prefix}"
  log_type     = "ACCESS_LOGS"
  resource_arn = aws_cloudfront_distribution.main.arn
}

resource "aws_cloudwatch_log_delivery" "cloudfront_logs" {
  count        = var.logging.logging_retention > 0 ? 1 : 0
  # provider     = aws.region
  delivery_source_name     = aws_cloudwatch_log_delivery_source.cloudfront_logs[0].name
  delivery_destination_arn = aws_cloudwatch_log_delivery_destination.cloudwatch_log_group[0].arn
}

resource "aws_cloudwatch_log_delivery_destination" "cloudwatch_log_group" {
  count        = var.logging.logging_retention > 0 ? 1 : 0
  # provider     = aws.region
  name          = "cloudwatch-access-logs-${var.resources_prefix}"
  output_format = "json"

  delivery_destination_configuration {
    destination_resource_arn = aws_cloudwatch_log_group.access_logs[0].arn
  }
}

```

**Comment by derekleegh** [comment]
@tkriviradev when you run `aws logs describe-delivery-source` command, are you sure its looking at us-east-1? 

a more confirm approach will be to add `aws logs describe-delivery-source --region us-east-1` to make sure.

**Comment by tkriviradev** [comment]
You are right, thank you for the help.

I just ended up in panic mode, after I was not able to confirm in
CloudWatch log delivery destination and source.

**Comment by jonb-ifit** [comment]
> ```
> resource "aws_cloudwatch_log_delivery_destination" "cloudfront_log_dest" {
>   name = "example-cloudfront-destination-logs"
> 
>   output_format = "parquet" //whatever output format you're using
> 
>   delivery_destination_configuration {
>     destination_resource_arn = "arn:aws:s3:::bucket-name/CloudFrontLogs"
>   }
> }
> ```
> 
> When this is referenced with the `aws_cloudwatch_log_delivery` resource, it results in a successful creation of the delivery that doesn't cause inconsistency errors, but there is an additional prefix in the log destination bucket.

@ekramer-starz 

I'm experiencing this issue even when the destination already does have a prefix destinaion arn:

> When applying changes to module.my_module.module.cloudfront_logging.aws_cloudwatch_log_delivery.delivery, provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value: .s3_delivery_configuration[0].suffix_path: was cty.StringVal("/{DistributionId}/{yyyy}/{MM}/{dd}"), but now cty.StringVal("AWSLogs/{account-id}/CloudFront/{DistributionId}/{yyyy}/{MM}/{dd}").

and I used aws logs get-delivery-destination to confirm:

```
{
    "deliveryDestination": {
        "name": "my-bucket-test",
        "arn": "arn:aws:logs:us-east-1:123456789012:delivery-destination:my-bucket-test",
        "deliveryDestinationType": "S3",
        "outputFormat": "parquet",
        "deliveryDestinationConfiguration": {
            "destinationResourceArn": "arn:aws:s3:::my-bucket/test"
        }
    }
}
```

**Comment by parsifail** [comment]
> I'm experiencing this issue even when the destination already does have a prefix destinaion arn:

I can confirm this too.
