### ISSUE TITLE
[Repo]: 5.86.1 registry metadata is missing for linux amd64

### ISSUE THREAD

**Issue by cdst** [hashicorp/terraform-provider-aws#41332]
### Description

The Linux amd64 version appears to be missing the registry metadata for the [5.86.1](https://registry.terraform.io/v1/providers/hashicorp/aws/5.86.1/download/linux/amd64) release

The binary is available through the [direct link](https://releases.hashicorp.com/terraform-provider-aws/5.86.1/terraform-provider-aws_5.86.1_linux_amd64.zip)

### References

https://registry.terraform.io/v1/providers/hashicorp/aws/5.86.1/download/linux/amd64 results in {"errors":["Not Found"]}

### Would you like to implement a fix?

None

**Comment by lpassig** [comment]
Should work now :) Visit: https://registry.terraform.io/v1/providers/hashicorp/aws/5.86.1/download/linux/amd64

**Comment by cdst** [comment]
Still shows as not found on my end

**Comment by nick-rakoczy** [comment]
This is the third time since August that metadata has been missing from registry.terraform.io for an AWS provider release (5.64.0, 5.71.0, and 5.86.1) on at least one platform.

5.64.0: https://github.com/hashicorp/terraform-provider-aws/issues/39012
5.71.0: https://github.com/hashicorp/terraform-provider-aws/issues/39706

Anyone that runs a private proxy cache that uses this metadata is effectively down if they're declaring versions like `~> 5`. Is there a plan to permanently address these issues going forward?

**Comment by Christofosho** [comment]
Seeing this as well. Hope for a resolution soon! Let me know if there is any information needed to help with this issue.

**Comment by Christofosho** [comment]
It may be that I am running into a different problem, but I am still getting this:

```
│ Error: missing or corrupted provider plugins:
│   - registry.terraform.io/hashicorp/archive: there is no package for registry.terraform.io/hashicorp/archive 2.7.0 cached in .terraform/providers
│   - registry.terraform.io/hashicorp/aws: there is no package for registry.terraform.io/hashicorp/aws 5.86.1 cached in .terraform/providers
```

**Comment by justinretzolk** [comment]
@Christofosho that does look like a separate issue based on the error received. I did find a couple of related issues ([here](https://github.com/hashicorp/terraform/issues/30122) and [here](https://github.com/hashicorp/terraform/issues/30314)) in the Terraform Core repository that seem to indicate that may be an issue stemming from the `.terraform.lock.hcl` file. It seems like that should have been resolved in newer versions of Terraform, but regardless, seems unrelated to this particular issue.

**Comment by justinretzolk** [comment]
Given that we've not heard back, and a number of releases have come out since this was initially filed, I'm going to close this issue. If anyone is still encountering issues downloading the provider, please open a new ticket to let us know.
