### ISSUE TITLE
Invalid AWS Region

### ISSUE THREAD

**Issue by scalp42** [hashicorp/terraform-provider-aws#8040]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.2.0
```

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-west-2"
  alias = "bridge"
  version = "~> 2.2.0"
}

data "aws_caller_identity" "bridge" {
  provider = "aws.bridge"
}

data "aws_iam_policy_document" "s3_changeme_terraform" {
  statement {
    #sid = "1"

    actions = [
      "s3:GetBucketLocation",
      "s3:GetBucketVersioning",
      "s3:GetObject",
      "s3:GetObjectVersion",
      "s3:ListBucket",
    ]

    effect = "Allow"

    resources = [
      "arn:aws:s3:::changeme-terraform",
    ]

    principals {
      type = "AWS"
      identifiers = [
        "arn:aws:iam::${data.aws_caller_identity.bridge.account_id}:root",
      ]
    }
  }
}
```

### Debug Output

Plan: https://gist.github.com/scalp42/c847168667233b4bf5b89e79dbaa7c0c

Apply: https://gist.github.com/scalp42/cd7644708890dfed55080c6d870a8b1f

### Expected Behavior

- it should not ask for the region
- it should pick up the region from the provider

### Actual Behavior

- will ask for AWS region
- will not create any resource mentioning an invalid AWS region

### Steps to Reproduce

1. `terraform plan -out terraform`
1. `terraform plan apply terraform`

### References

This issue relates to the region being asked: https://github.com/hashicorp/terraform/issues/20599

**Comment by scalp42** [comment]
It works if I force the region through env variable:

```
AWS_REGION=us-west-2 terraform xxx
```

But I don't think it's expected behavior as the region is specified in the provider.

**Comment by squidfunk** [comment]
Still happening for me on `terraform-0.12.1` and `terraform-provider-aws-2.13.0`

**Comment by MrSnappingTurtle** [comment]
In the off chance this helps someone who has the same issue but for a different reason, I had underscores instead of dashes.

**Comment by techiechap** [comment]
> In the off chance this helps someone who has the same issue but for a different reason, I accidentally had underscores instead of dashes.

Same issue, i had used underscore instead of -, thanks

**Comment by DrStrangepork** [comment]
> In the off chance this helps someone who has the same issue but for a different reason, I accidentally had underscores instead of dashes.

Underscores and dashes in what? `AWS_REGION` is the correct format with underscores.

**Comment by MrSnappingTurtle** [comment]
> > In the off chance this helps someone who has the same issue but for a different reason, I accidentally had underscores instead of dashes.
> 
> Underscores and dashes in what? `AWS_REGION` is the correct format with underscores.

If I recall correctly I did `us_west_2` instead of `us-west-2`.

**Comment by scalp42** [comment]
I think there's a new issue now: https://github.com/terraform-providers/terraform-provider-aws/issues/9617

**Comment by rehevkor5** [comment]
I had the same problem when using `terraform import` with a `-var-file` and aws provider like:
```
provider "aws" {
  region = var.region
}
```

I had to replace the variable with a hard-coded region in order to get it to work.

**Comment by mikhailadvani** [comment]
faced the same issue during import of resources with terraform v0.12.8 and AWS provider v2.26.0

**Comment by kartvep** [comment]
Same issue with provider.aws v2.29.0

**Comment by kartvep** [comment]
Looks like for import context is initialized with some short circuit.
If variable used for region doesn't have default value, import fails with ```Error: Invalid AWS Region:``` as described above.
But if default value added for this variable, import operation uses this value instead of given to module's parameter.

main.tf:
```
module "tst" {
  source = "./tst"
  region = "aws-ie"
}
```
tst/main.tf:
```
variable "region" {
   default = "WAT?"
}

local {
   regions = { "aws-ie" = "eu-west-1" }
}

provider "aws" {
  region = local.regions[var.region]
}
...
```
```terraform import module.tst.resource resource_id``` fails like this:
```
Error: Invalid index

  on tst/main.tf line 2, in provider "aws":
   2:   region = local.regions[var.region]
    |----------------
    | local.regions is object with 10 attributes
    | var.region is "WAT?"

The given key does not identify an element in this collection value.
```

**Comment by fernanen** [comment]
> In the off chance this helps someone who has the same issue but for a different reason, I accidentally had underscores instead of dashes.

Here is another silly case. I was passing an undeclared environment variable (sent nothing).
TF_VAR_aws_region=$AWS_REGION Terraform apply
After setting my variable AWS_REGION with the right region - I was able to proceed with the build.

**Comment by vianel** [comment]
faced the same issue   terraform = 0.12.20
 "aws"  version = "~> 2.45.0"

this works for me 👇 
> I had to replace the variable with a hard-coded region in order to get it to work.

**Comment by jessesanford** [comment]
Same here with "aws" version 2.40.0

**Comment by vazhnov** [comment]
The same problem with "profile" too, not only "region". I couldn't do import until hardcoded profile name.

Error message:
```
Error: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider
```

terraform = 0.12.20, through tfenv.
provider.aws 2.49

**Comment by n8gard** [comment]
Just had the same problem w/
```
terraform --version
Terraform v0.12.23
+ provider.aws v2.52.0
+ provider.random v2.2.1
```
Fixed w/ hardcoding in the `.terraform/modules` directory and then `import`ing.

**Comment by llamahunter** [comment]
This seems to be a deep terraform bug in the way `import` runs vs `plan` or `apply` . https://github.com/hashicorp/terraform/issues/13018

**Comment by amitcloudworld** [comment]
Region name must be like this other wise you will get error for region ok  region= "us-west-1a"  you need to remove a this is the right way to keep your regino name region     = "us-west-1"

happy 
![ERROR MSG TO LOGIN ECT IN TERRAFORM](https://user-images.githubusercontent.com/67389359/85845597-58529180-b759-11ea-8ee5-778badb12c58.png)

**Comment by sosimon** [comment]
I have run into this a few times now - I end up manually editing all the providers in all my modules inside `.terraform` from 
```
provider "aws" {
  region = var.region
}
```
to 
```
provider "aws" {
  region = "us-east-1"
}
```
and then `tf import` again.

**Comment by dyegoe** [comment]
I don't know if it is related, but the error is the same, at least. Still happen on v0.15.0 + AWS v3.37.0

```
Terraform v0.15.0
+ provider registry.terraform.io/hashicorp/aws v3.37.0
```

```
#########################
locals {
  region               = "eu-north-1"
  resource_name_prefix = "elastic-lab"
  common_tags = {
    project     = "elastic-lab"
    workspace   = "elastic-lab"
    environment = "lab"
    region      = "${local.region}"
    terraform   = "true"
  }
}

#########################
provider "aws" {
  region = local.region
}
```

If I plan, it goes well
```
% terraform plan -out deploy.plan
module.vpc.aws_vpc.this[0]: Refreshing state... [id=vpc-04059f72fbd29c65a]
module.vpc.aws_subnet.public[0]: Refreshing state... [id=subnet-048d25053a9462e08]
module.vpc.aws_subnet.public[2]: Refreshing state... [id=subnet-06e137f834aafb643]
module.vpc.aws_subnet.public[1]: Refreshing state... [id=subnet-05292f8ea1a41e5d2]
module.vpc.aws_route_table.public[0]: Refreshing state... [id=rtb-03f14abf8d3dbcff3]
module.vpc.aws_internet_gateway.this[0]: Refreshing state... [id=igw-04ef51cea1a9b3432]
module.vpc.aws_route.public_internet_gateway[0]: Refreshing state... [id=r-rtb-03f14abf8d3dbcff31080289494]
module.vpc.aws_route_table_association.public[0]: Refreshing state... [id=rtbassoc-04433f9202cebccf9]
module.vpc.aws_route_table_association.public[2]: Refreshing state... [id=rtbassoc-0c75e1cf254ec8112]
module.vpc.aws_route_table_association.public[1]: Refreshing state... [id=rtbassoc-096033c5f5206f58e]

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your configuration and the remote system(s). As a result, there are no actions to take.
```

But if I try to destroy
```
% terraform destroy              
module.vpc.aws_vpc.this[0]: Refreshing state... [id=vpc-04059f72fbd29c65a]
module.vpc.aws_internet_gateway.this[0]: Refreshing state... [id=igw-04ef51cea1a9b3432]
module.vpc.aws_route_table.public[0]: Refreshing state... [id=rtb-03f14abf8d3dbcff3]
module.vpc.aws_subnet.public[2]: Refreshing state... [id=subnet-06e137f834aafb643]
module.vpc.aws_subnet.public[0]: Refreshing state... [id=subnet-048d25053a9462e08]
module.vpc.aws_subnet.public[1]: Refreshing state... [id=subnet-05292f8ea1a41e5d2]
module.vpc.aws_route.public_internet_gateway[0]: Refreshing state... [id=r-rtb-03f14abf8d3dbcff31080289494]
module.vpc.aws_route_table_association.public[2]: Refreshing state... [id=rtbassoc-0c75e1cf254ec8112]
module.vpc.aws_route_table_association.public[0]: Refreshing state... [id=rtbassoc-04433f9202cebccf9]
module.vpc.aws_route_table_association.public[1]: Refreshing state... [id=rtbassoc-096033c5f5206f58e]
╷
│ Error: Invalid AWS Region: 
│ 
│   on main.tf line 19, in provider "aws":
│   19: provider "aws" {
│ 
```

**Comment by freakinhippie** [comment]
I am seeing this issue too, using terraform v0.15.0, and aws v3.37.0.

**Comment by bflad** [comment]
It looks like this is a bug upstream in Terraform CLI version 0.15.0 (https://github.com/hashicorp/terraform/issues/28428 / https://github.com/hashicorp/terraform/pull/28444), which could be addressed next Terraform CLI release.

**Comment by saivarunr** [comment]
Works fine when apply, destroy does not work.

╷
│ Error: Invalid AWS Region: 
│ 
│   on .terraform/modules/deploy-eks/main.tf line 24, in provider "aws":
│   24: provider "aws" {
│ 
╵


However, had to edit the file `deploy-eks/main.tf` inside `.terraform` directory to make destroy work.

**Comment by saivarunr** [comment]
We could circumvent this by configuring the aws provider in the parent module, passing it to deploy-eks module as provider.

**Comment by pschulten** [comment]
I just build the CLI from main, and it fixes it

**Comment by brikis98** [comment]
Seeing the same issue. `apply` works fine, but on `destroy`, any nested `provider` block with `region` set to a variable gives an "Invalid AWS Region" error.

**Comment by brikis98** [comment]
BTW, this worked fine with Terraform 0.14.x, but is newly broken with Terraform 0.15.x.

**Comment by anton-demydov-zoral** [comment]
seems it was fixed in 0.15.1

**Comment by antondemidov** [comment]
seems it was fixed in 0.15.1

**Comment by mhvelplund** [comment]
> seems it was fixed in 0.15.1

I tried with 0.15.4 and it workd. So; with 0.15.0 I can init and plan, but not destroy. Bug seems fixed in the subsequent patch 🤷‍♀️

**Comment by breathingdust** [comment]
Closing this as this appears to have been resolved in an upstream Terraform patch landing in 0.15.1. If I have closed this in error, do let me know and I will reopen.

**Comment by markhuge** [comment]
seems to have resurfaced in 1.1.7 with aws provider 4.4.0.

`terraform plan` fails when the region is set from the provider config, but will proceed if I set an env var:

```
provider "aws" {
  region = "us-west-2"
  alias = "west"
}
```

`Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, failed to resolve service endpoint, an AWS region is required, but was not found
`
